# Generated by Django 2.2.27 on 2022-04-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videopage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the video",
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
