# Generated by Django 2.2.27 on 2022-04-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20220406_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Field that determines whether the video is featured in the list page.', verbose_name='Is Featured'),
        ),
    ]
