# Generated by Django 2.2.28 on 2022-05-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('videos', '0004_videopage_thumbnail_image_alt_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoPage',
        ),
    ]
