# Generated by Django 2.2.28 on 2022-05-18 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('videos', '0005_delete_videopage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('embed_url', models.CharField(blank=True, help_text='This needs to be the embed URL of the video or else the video player will not work', max_length=100, null=True, verbose_name='Embed URL')),
                ('thumbnail_image_alt_text', models.CharField(blank=True, help_text='Alt text for the thumbnail image', max_length=100, null=True, verbose_name='Thumbnail Image Alt Text')),
                ('description', models.TextField(blank=True, help_text='Description of the video', null=True, verbose_name='Description')),
                ('is_featured', models.BooleanField(default=False, help_text='Field that determines whether the video is featured in the list page.', verbose_name='Is Featured')),
                ('thumbnail_image', models.ForeignKey(blank=True, help_text='Thumbnail image that is going to be displayed for the video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
