# Generated by Django 2.2.28 on 2022-11-28 06:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20220603_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoindexpage',
            name='media_hub_section_header_title',
            field=models.CharField(blank=True, help_text='Set text for Media Hub Section Header Title', max_length=255, null=True, verbose_name='Media Hub Section Header Title'),
        ),
        migrations.CreateModel(
            name='VideosMediaHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('media_hub_item', models.CharField(blank=True, help_text='Set text for Media Hub Item', max_length=255, null=True, verbose_name='Media Hub Item')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_hub_videos_list', to='videos.VideoIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
