# Generated by Django 2.2.28 on 2022-11-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20221128_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoindexpage',
            name='register_login_button',
            field=models.CharField(blank=True, help_text='Set text for Register and Login Button Text', max_length=255, null=True, verbose_name='Register and Login Button Text'),
        ),
    ]
