# Generated by Django 2.2.28 on 2022-12-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_videoindexpage_register_login_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoindexpage',
            name='register_login_button',
        ),
        migrations.AddField(
            model_name='videoindexpage',
            name='login_button',
            field=models.CharField(blank=True, help_text='Set text for Login Button Text', max_length=100, null=True, verbose_name='Login Button Text'),
        ),
        migrations.AddField(
            model_name='videoindexpage',
            name='register_button',
            field=models.CharField(blank=True, help_text='Set text for Register Button Text', max_length=100, null=True, verbose_name='Register Button Text'),
        ),
    ]
