# Generated by Django 2.2.28 on 2022-12-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20221206_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopage',
            name='is_featured',
        ),
    ]
