# Generated by Django 2.2.28 on 2022-05-25 14:26

from django.db import migrations, models
import django.db.models.deletion
import home.utils
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualMissionaryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('introduction', models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Introduction')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Missionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the missionary', max_length=255, null=True, verbose_name='Name')),
                ('country', models.CharField(blank=True, help_text='Country of the missionary', max_length=255, null=True, verbose_name='Country')),
                ('region', models.CharField(blank=True, help_text='Region of the missionary', max_length=255, null=True, verbose_name='Region')),
                ('image', models.ImageField(blank=True, help_text='Image of the missionary', null=True, upload_to=home.utils.get_upload_path, verbose_name='Image')),
                ('image_alt_text', models.CharField(blank=True, help_text='Alt text for the image of the missionary', max_length=255, null=True, verbose_name='Image Alt Text')),
                ('account_number', models.CharField(blank=True, help_text='Account number of the missionary', max_length=255, null=True, verbose_name='Account Number')),
                ('email_address', models.EmailField(help_text='Email address of the missionary', max_length=255, null=True, verbose_name='Email Address')),
                ('website_link', models.CharField(blank=True, help_text='Website link of the missionary', max_length=255, null=True, verbose_name='Website Link')),
                ('home_phone_number', models.CharField(blank=True, help_text='Home phone number of the missionary', max_length=255, null=True, verbose_name='Home Phone Number')),
                ('mobile_number', models.CharField(blank=True, help_text='Mobile number of the missionary', max_length=255, null=True, verbose_name='Mobile Number')),
                ('facebook_link', models.CharField(blank=True, help_text='Facebook link of the missionary. Make sure to attach the https url or else the page will return an error', max_length=255, null=True, verbose_name='Facebook Link')),
                ('instagram_link', models.CharField(blank=True, help_text='Instagram link of the missionary. Make sure to attach the https url or else the page will return an error', max_length=255, null=True, verbose_name='Instagram Link')),
            ],
            options={
                'verbose_name': 'Missionary',
                'verbose_name_plural': 'Missionaries',
            },
        ),
        migrations.CreateModel(
            name='IndividualMissionaryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('about', wagtail.core.fields.RichTextField(blank=True, help_text='About section of the page', null=True, verbose_name='About')),
                ('header_image_alt_text', models.CharField(blank=True, help_text='Alt text for the header image of the missionary', max_length=255, null=True, verbose_name='Header Image Alt Text')),
                ('header_map_image_alt_text', models.CharField(blank=True, help_text='Alt text for the header map image of the missionary', max_length=255, null=True, verbose_name='Header Map Image Alt Text')),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image that is going to be displayed for the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('header_map_image', models.ForeignKey(blank=True, help_text='Header map image that is going to be displayed for the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('missionary', models.ForeignKey(blank=True, help_text='Missionary of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_missionaries', to='individual_missionaries.Missionary', verbose_name='missionary')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
