# Generated by Django 2.2.28 on 2022-06-14 18:51

from django.db import migrations, models
import django.db.models.deletion
import home.utils


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20220610_1052'),
        ('individual_missionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionaryRegionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.FileField(blank=True, help_text='Background image that will be shown in the header portion of the page', null=True, upload_to=home.utils.get_upload_path, verbose_name='Header Image')),
                ('header_image_alt_text', models.CharField(blank=True, help_text='Alt text for the header image', max_length=255, null=True, verbose_name='Header Image Alt Text')),
                ('header_map_image', models.FileField(blank=True, help_text='Image that will be shown in the map portion in the header of the page', null=True, upload_to=home.utils.get_upload_path, verbose_name='Header Map Image')),
                ('header_map_image_alt_text', models.CharField(blank=True, help_text='Alt text for the map image in the header of the page', max_length=100, null=True, verbose_name='Header Map Image Alt Text')),
                ('region', models.OneToOneField(help_text='Region assigned for the iamges', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='cms.Region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Missionary Region Image',
                'verbose_name_plural': 'Missionary Region Images',
            },
        ),
    ]
