# Generated by Django 2.2.28 on 2022-06-16 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individual_missionaries', '0002_missionaryregionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionaryregionimage',
            name='region',
            field=models.ForeignKey(help_text='Region assigned for the iamges', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missionary_region_images', to='cms.Region', verbose_name='Region'),
        ),
    ]
