# Generated by Django 2.2.28 on 2022-09-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual_missionaries', '0004_auto_20220701_0234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionaryRegionImage',
        ),
    ]
