# Generated by Django 2.2.28 on 2022-12-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_missionaries', '0005_delete_missionaryregionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualmissionaryindexpage',
            name='about_header_text',
            field=models.CharField(blank=True, help_text='About header text in about section.', max_length=255, null=True, verbose_name='About Header Text'),
        ),
        migrations.AddField(
            model_name='individualmissionaryindexpage',
            name='account_text',
            field=models.CharField(blank=True, help_text='Account text next to account number.', max_length=255, null=True, verbose_name='Account Text'),
        ),
        migrations.AddField(
            model_name='individualmissionaryindexpage',
            name='give_button_text',
            field=models.CharField(blank=True, help_text='Text of the give button.', max_length=255, null=True, verbose_name='Give Button Text'),
        ),
        migrations.AddField(
            model_name='individualmissionaryindexpage',
            name='give_to_content',
            field=models.TextField(blank=True, help_text='Give to content displayed below the give to section header.', null=True, verbose_name='Give to Content'),
        ),
        migrations.AddField(
            model_name='individualmissionaryindexpage',
            name='give_to_text',
            field=models.CharField(blank=True, help_text='Give to text next to individual missionary name in give section header.', max_length=255, null=True, verbose_name='Give to Text'),
        ),
        migrations.AddField(
            model_name='individualmissionaryindexpage',
            name='home_text',
            field=models.CharField(blank=True, help_text='Home text next to phone number.', max_length=255, null=True, verbose_name='Home Text'),
        ),
        migrations.AddField(
            model_name='individualmissionaryindexpage',
            name='serving_in_text',
            field=models.CharField(blank=True, help_text='Serving in text beside individual missionary region.', max_length=255, null=True, verbose_name='Serving in Text'),
        ),
        migrations.AddField(
            model_name='individualmissionaryindexpage',
            name='start_your_gift_today_button_text',
            field=models.CharField(blank=True, help_text='Start your gift today button text at the bottom of give to section.', max_length=255, null=True, verbose_name='Start Your Gift Today Button Text'),
        ),
    ]
