# Generated by Django 2.2.28 on 2022-07-12 09:15

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header_image_alt_text', models.CharField(blank=True, help_text='Alt text for the header image', max_length=255, null=True, verbose_name='Header Image Alt Text')),
                ('header_title', models.CharField(blank=True, help_text='Text that will be shown in the title poriton in the header of the page', max_length=255, null=True, verbose_name='Header Title')),
                ('header_content', models.TextField(blank=True, help_text='Text that will be shown under the header title', null=True, verbose_name='Header Content')),
                ('mission_content', wagtail.core.fields.RichTextField(blank=True, help_text='Content/Text that will be shown below the header portion of the page', null=True, verbose_name='Mission Content')),
                ('team_section_title', models.CharField(blank=True, help_text="Text that will be shown in the 'Executive Team' section of the page", max_length=255, null=True, verbose_name='Team Section Header')),
                ('world_missions_title', models.CharField(blank=True, help_text="Text that will be shown for the 'World Missions' section of the page", max_length=255, null=True, verbose_name='World Missions Title')),
                ('world_missions_image_alt_text', models.CharField(blank=True, help_text='Alt text for the world missions image', max_length=255, null=True, verbose_name='World Missions Image Alt Text')),
                ('header_image', models.ForeignKey(blank=True, help_text='Image that will be shown in the header portion of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header Image')),
                ('world_missions_image', models.ForeignKey(blank=True, help_text='Image that will be shown under the world missions title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='World Missions Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ExecutiveTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Name of the Executive Team member', max_length=255, null=True, verbose_name='Name')),
                ('position', models.CharField(help_text='Position of the Executive Team member', max_length=255, null=True, verbose_name='Position')),
                ('order', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('others', 'Others')], help_text='Order in the list of team members that will be displayed. Example: Executive Director would be first etc.', max_length=100, verbose_name='Order')),
                ('photo_alt_text', models.CharField(blank=True, help_text='Alt text for the image', max_length=255, null=True, verbose_name='Image Alt Text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_team_members', to='about.AboutPage')),
                ('photo', models.ForeignKey(blank=True, help_text='Photo of the Executive Team member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
