# Generated by Django 2.2.28 on 2022-12-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='mission_content_readmore_button_text',
            field=models.CharField(blank=True, help_text='Readmore button text below the content. ', max_length=255, null=True, verbose_name='Mission Content Readmore Button Text'),
        ),
    ]
