# Generated by Django 2.2.28 on 2022-12-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpage_mission_content_readmore_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='mission_content_readmore_button_text',
        ),
    ]
