# Generated by Django 2.2.28 on 2022-05-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("stories", "0002_storypage_image_alt_text"),
        ("cms", "0007_socialmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "header_sub_text",
                    models.TextField(
                        blank=True,
                        help_text="Text at the bottom of the name of the region in the header portion of the region page",
                        null=True,
                        verbose_name="Header Sub-text",
                    ),
                ),
                (
                    "header_bottom_text",
                    models.TextField(
                        blank=True,
                        help_text="Text at the bottom area of the header portion of the region page",
                        null=True,
                        verbose_name="Header Bottom Text",
                    ),
                ),
                (
                    "header_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the header image",
                        max_length=100,
                        null=True,
                        verbose_name="Header Image Alt Text",
                    ),
                ),
                (
                    "header_background_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the header background image",
                        max_length=100,
                        null=True,
                        verbose_name="Header Background Image Alt Text",
                    ),
                ),
                (
                    "header_map_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the map image in the header of the region page",
                        max_length=100,
                        null=True,
                        verbose_name="Header Map Image Alt Text",
                    ),
                ),
                (
                    "giving_initiative_title",
                    models.CharField(
                        blank=True,
                        help_text="The title for the giving initiative section for the region page",
                        max_length=100,
                        null=True,
                        verbose_name="Giving Initiative Title",
                    ),
                ),
                (
                    "giving_initiative_body",
                    models.TextField(
                        blank=True,
                        help_text="The body part for the giving initiative section for the region page",
                        null=True,
                        verbose_name="Giving Initiative Body",
                    ),
                ),
                (
                    "giving_initiative_background_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the background image in the giving initiative portion of the region page",
                        max_length=100,
                        null=True,
                        verbose_name="Giving Initiative Background Image Alt Text",
                    ),
                ),
                (
                    "director_name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the director for the region",
                        max_length=100,
                        null=True,
                        verbose_name="Director Name",
                    ),
                ),
                (
                    "director_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the director image",
                        max_length=100,
                        null=True,
                        verbose_name="Director Image Alt Text",
                    ),
                ),
                (
                    "director_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="The phone number of the director for the region",
                        max_length=225,
                        null=True,
                        verbose_name="Director Phone Number",
                    ),
                ),
                (
                    "region_website_link",
                    models.CharField(
                        blank=True,
                        help_text="The website link for the region",
                        max_length=225,
                        null=True,
                        verbose_name="Region Website Link",
                    ),
                ),
                (
                    "region_facebook_link",
                    models.CharField(
                        blank=True,
                        help_text="The facebook link for the region",
                        max_length=225,
                        null=True,
                        verbose_name="Region Facebook Link",
                    ),
                ),
                (
                    "population_number",
                    models.CharField(
                        blank=True,
                        help_text="The website link for the region",
                        max_length=225,
                        null=True,
                        verbose_name="Population Number",
                    ),
                ),
                (
                    "spiritualy_lost",
                    models.CharField(
                        blank=True,
                        help_text="Number of spiritualy lost people",
                        max_length=225,
                        null=True,
                        verbose_name="Spiritualy Lost",
                    ),
                ),
                (
                    "unreached_people_groups",
                    models.CharField(
                        blank=True,
                        help_text="Number of unreached people groups",
                        max_length=225,
                        null=True,
                        verbose_name="Unreached People Groups",
                    ),
                ),
                (
                    "ag_constituents",
                    models.CharField(
                        blank=True,
                        help_text="Number of AG Constituents",
                        max_length=225,
                        null=True,
                        verbose_name="AG Constituents",
                    ),
                ),
                (
                    "ag_churches",
                    models.CharField(
                        blank=True,
                        help_text="Number of ag churches",
                        max_length=225,
                        null=True,
                        verbose_name="AG Churches",
                    ),
                ),
                (
                    "ag_ministers",
                    models.CharField(
                        blank=True,
                        help_text="Number of ag ministers",
                        max_length=225,
                        null=True,
                    ),
                ),
                (
                    "missionaries_and_associates",
                    models.CharField(
                        blank=True,
                        help_text="Number of missionaries and associates",
                        max_length=225,
                        null=True,
                        verbose_name="Missionaries and Associates",
                    ),
                ),
                (
                    "director_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image of the director for the region",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "giving_initiative_background_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Background image that will be shown in the giving initiative portion of the region page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "header_background_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will be shown in the background of the header portion of the region page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will be shown in the header portion of the region page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "header_map_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will be shown in the map portion in the header of the region page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "stories_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Story section of the page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stories.StoryIndexPage",
                        verbose_name="Story Section",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="RegionIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True,
                        help_text="Text to describe the page",
                        verbose_name="Introduction",
                    ),
                ),
                (
                    "mission_text",
                    models.CharField(
                        blank=True,
                        help_text="Text in the mission section of the Region Page",
                        max_length=100,
                        null=True,
                        verbose_name="Mission Text",
                    ),
                ),
                (
                    "africa_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the Africa region image",
                        max_length=100,
                        null=True,
                        verbose_name="Africa Alt Text",
                    ),
                ),
                (
                    "asia_pacific_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the Asia Pacific region image",
                        max_length=100,
                        null=True,
                        verbose_name="Asia Pacific Alt Text",
                    ),
                ),
                (
                    "eurasia_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the Eurasia region image",
                        max_length=100,
                        null=True,
                        verbose_name="Eurasia Alt Text",
                    ),
                ),
                (
                    "europe_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the Europe region image",
                        max_length=100,
                        null=True,
                        verbose_name="Europe Alt Text",
                    ),
                ),
                (
                    "international_ministries_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the International Ministries image",
                        max_length=100,
                        null=True,
                        verbose_name="International Ministries Alt Text",
                    ),
                ),
                (
                    "latin_america_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the Latin America region image",
                        max_length=100,
                        null=True,
                        verbose_name="Latin America Alt Text",
                    ),
                ),
                (
                    "northern_asia_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the Northern America region image",
                        max_length=100,
                        null=True,
                        verbose_name="Northern America Alt Text",
                    ),
                ),
                (
                    "africa_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will be shown for the Africa region",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "asia_pacific_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will be shown for the Asia Pacific region",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "eurasia_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will be shown for the Eurasia region",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "europe_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will be shown for the Europe region",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "greg_mundis_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Greg mundis section of the page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.GregMundisInitiative",
                        verbose_name="Greg Mundis Section",
                    ),
                ),
                (
                    "international_ministries_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will be shown for the international ministries",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "latin_america_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will be shown for the Latin America region",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "northern_asia_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will be shown for the Northern America region",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
