# Generated by Django 2.2.28 on 2022-06-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionindexpage',
            name='header_background_image',
            field=models.ForeignKey(blank=True, help_text='Image that will be shown in the background of the header portion of the region page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='regionindexpage',
            name='header_background_image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the header background image', max_length=100, null=True, verbose_name='Header Background Image Alt Text'),
        ),
    ]
