# Generated by Django 2.2.28 on 2022-10-05 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20220607_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionpage',
            name='region_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='regions.RegionIndexPage'),
        ),
    ]
