# Generated by Django 2.2.28 on 2022-11-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_regionpage_header_join_the_team_button_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionindexpage',
            name='find_more_button',
            field=models.CharField(blank=True, help_text='Set text for the Find more button', max_length=100, null=True, verbose_name='Find More Button Text'),
        ),
        migrations.AddField(
            model_name='regionindexpage',
            name='region_map_header_title',
            field=models.CharField(blank=True, help_text='Set text for Region Map Header Title', max_length=100, null=True, verbose_name='Region Map Header Title'),
        ),
    ]
