# Generated by Django 2.2.28 on 2022-11-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_auto_20221128_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionindexpage',
            name='find_more_button',
        ),
        migrations.RemoveField(
            model_name='regionindexpage',
            name='region_map_header_title',
        ),
        migrations.AddField(
            model_name='regionpage',
            name='ag_churches_card_text',
            field=models.CharField(blank=True, help_text='Set text for AG Churches Card', max_length=255, null=True, verbose_name='AG Churches Card Text'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='ag_constituents_card_text',
            field=models.CharField(blank=True, help_text='Set text for AG Constituents Card', max_length=255, null=True, verbose_name='AG Constituents Card Text'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='ag_ministers_card_text',
            field=models.CharField(blank=True, help_text='Set text for AG Ministers Card', max_length=255, null=True, verbose_name='AG Ministers Card Text'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='director_header_title',
            field=models.CharField(blank=True, help_text='Set text for Director Header Title', max_length=255, null=True, verbose_name='Director Header Title Text'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='find_more_button',
            field=models.CharField(blank=True, help_text='Set text for the Find more button', max_length=100, null=True, verbose_name='Find More Button Text'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='giving_initiative_header_title',
            field=models.CharField(blank=True, help_text='Set text for Giving Initiative Header Title', max_length=255, null=True, verbose_name='Giving Initiative Header Title'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='join_the_team_button',
            field=models.CharField(blank=True, help_text='Set text for Join the Team Button', max_length=225, null=True, verbose_name='Join the Team Button'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='missionaries_and_associates_card_text',
            field=models.CharField(blank=True, help_text='Set text for Missionaries and Associates Card', max_length=255, null=True, verbose_name='Missionaries and Associates Card Text'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='phone_number_text',
            field=models.CharField(blank=True, help_text='Set text for Phone Number', max_length=255, null=True, verbose_name='Phone Number Text'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='population_section_title',
            field=models.CharField(blank=True, help_text='Set text for Population Section Title', max_length=255, null=True, verbose_name='Population Section Title Text'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='region_map_header_title',
            field=models.CharField(blank=True, help_text='Set text for Region Map Header Title', max_length=100, null=True, verbose_name='Region Map Header Title'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='regional_web_site_button',
            field=models.CharField(blank=True, help_text='Set text for Regional Web Site', max_length=255, null=True, verbose_name='Regional Web Site Text'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='related_ministries_links_text',
            field=models.CharField(blank=True, help_text='Set text for Related Ministries Links', max_length=255, null=True, verbose_name='Related Ministries Links Text'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='spiritually_lost_card_text',
            field=models.CharField(blank=True, help_text='Set text for Spiritually Lost Card', max_length=255, null=True, verbose_name='Spiritually Lost Card Text'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='start_your_gift_button',
            field=models.CharField(blank=True, help_text='Set text for Start Your Gift Button', max_length=255, null=True, verbose_name='Start Your Gift Button Text'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='stories_header_sub_title',
            field=models.CharField(blank=True, help_text='Set text for Stories Header Sub Title', max_length=255, null=True, verbose_name='Stories Header Sub Title'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='stories_header_title',
            field=models.CharField(blank=True, help_text='Set text for Stories Header', max_length=255, null=True, verbose_name='Stories Header Title'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='stories_read_all_button_text',
            field=models.CharField(blank=True, help_text='Set text for Stories Read All Button', max_length=255, null=True, verbose_name='Stories Read All Button Text'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='unreached_people_groups_card_text',
            field=models.CharField(blank=True, help_text='Set text for Unreached People Groups Card', max_length=255, null=True, verbose_name='Unreached People Groups Card Text'),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='view_button',
            field=models.CharField(blank=True, help_text='Set text for View Text in Regional Web Site', max_length=255, null=True, verbose_name='View Text in Regional Web Site'),
        ),
    ]
