# Generated by Django 2.2.28 on 2022-12-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_auto_20221128_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionpage',
            name='find_more_button',
        ),
        migrations.RemoveField(
            model_name='regionpage',
            name='region_map_header_title',
        ),
        migrations.AddField(
            model_name='regionindexpage',
            name='find_more_button',
            field=models.CharField(blank=True, help_text='Set text for the Find more button', max_length=100, null=True, verbose_name='Find More Button Text'),
        ),
        migrations.AddField(
            model_name='regionindexpage',
            name='region_map_header_title',
            field=models.CharField(blank=True, help_text='Set text for Region Map Header Title', max_length=100, null=True, verbose_name='Region Map Header Title'),
        ),
    ]
