# Generated by Django 2.2.27 on 2022-04-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeindexpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Introduction'),
        ),
    ]
