# Generated by Django 2.2.28 on 2022-07-01 09:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('explore_ways_to_serve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTermFirstTabQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('qualification', models.TextField(help_text='Text for the qualification of the section', null=True, verbose_name='Qualification')),
                ('page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_term_first_tab_qualification', to='explore_ways_to_serve.ExploreWaysToServe')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShortTermSecondTabQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('qualification', models.TextField(help_text='Text for the qualification of the section', null=True, verbose_name='Qualification')),
                ('page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_term_second_tab_qualification', to='explore_ways_to_serve.ExploreWaysToServe')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShortTermThirdTabQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('qualification', models.TextField(help_text='Text for the qualification of the section', null=True, verbose_name='Qualification')),
                ('page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_term_third_tab_qualification', to='explore_ways_to_serve.ExploreWaysToServe')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ShortTermQualificationFirstTab',
        ),
        migrations.DeleteModel(
            name='ShortTermQualificationSecondTab',
        ),
        migrations.DeleteModel(
            name='ShortTermQualificationThirdTab',
        ),
        migrations.AlterModelOptions(
            name='careerapplicationprocess',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='careerqualification',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='onetotwoyearapplicationprocess',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='onetotwoyearqualification',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='careerapplicationprocess',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_application_process', to='explore_ways_to_serve.ExploreWaysToServe'),
        ),
        migrations.AddField(
            model_name='careerapplicationprocess',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='careerqualification',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_qualification', to='explore_ways_to_serve.ExploreWaysToServe'),
        ),
        migrations.AddField(
            model_name='careerqualification',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='onetotwoyearapplicationprocess',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_to_two_year_application_process', to='explore_ways_to_serve.ExploreWaysToServe'),
        ),
        migrations.AddField(
            model_name='onetotwoyearapplicationprocess',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='onetotwoyearqualification',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_to_two_year_qualification', to='explore_ways_to_serve.ExploreWaysToServe'),
        ),
        migrations.AddField(
            model_name='onetotwoyearqualification',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='careerapplicationprocess',
            name='description',
            field=models.TextField(help_text='Description of the application process', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='careerapplicationprocess',
            name='title',
            field=models.TextField(help_text='Title of the application process', null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='careerqualification',
            name='qualification',
            field=models.TextField(help_text='Text for the qualification of the section', null=True, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='onetotwoyearapplicationprocess',
            name='description',
            field=models.TextField(help_text='Description of the application process', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='onetotwoyearapplicationprocess',
            name='title',
            field=models.TextField(help_text='Title of the application process', null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='onetotwoyearqualification',
            name='qualification',
            field=models.TextField(help_text='Text for the qualification of the section', null=True, verbose_name='Qualification'),
        ),
    ]
