# Generated by Django 2.2.28 on 2022-12-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore_ways_to_serve', '0002_auto_20220701_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorewaystoserve',
            name='begin_application_button_text',
            field=models.CharField(blank=True, help_text='Begin application button text at the bottom of the opportunity section.', max_length=255, null=True, verbose_name='Begin Application Button Text'),
        ),
        migrations.AddField(
            model_name='explorewaystoserve',
            name='career_apply_now_button_text',
            field=models.CharField(blank=True, help_text="Text for the 'Apply Now' button", max_length=255, null=True, verbose_name='Career Apply Now Button Text'),
        ),
        migrations.AddField(
            model_name='explorewaystoserve',
            name='career_last_section_button_text',
            field=models.TextField(blank=True, help_text='Text for the Last Section button', null=True, verbose_name='Career Last Section Button Text'),
        ),
        migrations.AddField(
            model_name='explorewaystoserve',
            name='career_qualifications_button_text',
            field=models.CharField(blank=True, help_text='Text for the qualifications button', max_length=255, null=True, verbose_name='Career Qualifications Button Text'),
        ),
        migrations.AddField(
            model_name='explorewaystoserve',
            name='email_mapstreams_button_text',
            field=models.CharField(blank=True, help_text='Email mapstreams button text at the bottom of the opportunity section.', max_length=255, null=True, verbose_name='Email Mapstreams Button Text'),
        ),
        migrations.AddField(
            model_name='explorewaystoserve',
            name='header_tab_career_text',
            field=models.CharField(blank=True, help_text='Career tab text in header.', max_length=100, null=True, verbose_name='Career Tab Text'),
        ),
        migrations.AddField(
            model_name='explorewaystoserve',
            name='header_tab_one_to_two_year_text',
            field=models.CharField(blank=True, help_text='1 - 2 year term tab text in header.', max_length=100, null=True, verbose_name='1 - 2 Year Tab Text'),
        ),
        migrations.AddField(
            model_name='explorewaystoserve',
            name='header_tab_short_term_text',
            field=models.CharField(blank=True, help_text='Short term tab text in header.', max_length=100, null=True, verbose_name='Short Term Tab Text'),
        ),
        migrations.AddField(
            model_name='explorewaystoserve',
            name='last_section_button_text',
            field=models.CharField(blank=True, help_text='Button text at the last section of the page.', max_length=255, null=True, verbose_name='Last Section Button Title'),
        ),
        migrations.AddField(
            model_name='explorewaystoserve',
            name='one_to_two_year_apply_now_button_text',
            field=models.CharField(blank=True, help_text="Text for the 'Apply Now' button", max_length=255, null=True, verbose_name='One To Two Year Apply Now Button Text'),
        ),
        migrations.AddField(
            model_name='explorewaystoserve',
            name='one_to_two_year_last_section_first_button_text',
            field=models.CharField(blank=255, help_text='Text for the first button', max_length=255, null=255, verbose_name='One To Two Year Last Section First Button Text'),
            preserve_default=255,
        ),
        migrations.AddField(
            model_name='explorewaystoserve',
            name='one_to_two_year_last_section_second_button_text',
            field=models.CharField(blank=255, help_text='Text for the second button', max_length=255, null=255, verbose_name='One To Two Year Last Section Second Button Text'),
            preserve_default=255,
        ),
        migrations.AddField(
            model_name='explorewaystoserve',
            name='one_to_two_year_last_section_third_button_text',
            field=models.CharField(blank=255, help_text='Text for the third button', max_length=255, null=255, verbose_name='One To Two Year Last Section Third Button Text'),
            preserve_default=255,
        ),
        migrations.AddField(
            model_name='explorewaystoserve',
            name='one_to_two_year_qualifications_button_text',
            field=models.CharField(blank=True, help_text='Text for the qualifications button', max_length=255, null=True, verbose_name='One To Two Year Qualifications Button Text'),
        ),
        migrations.AddField(
            model_name='explorewaystoserve',
            name='one_to_two_year_start_today_button_text',
            field=models.CharField(blank=True, help_text='Text for the start today button of the page', max_length=255, null=True, verbose_name='One To Two Year Start Today Button Text'),
        ),
    ]
