# Generated by Django 2.2.28 on 2022-06-07 09:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("stories", "0003_storypage_simple_prayer"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualMinistryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "header_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the header image of the ministry",
                        max_length=255,
                        null=True,
                        verbose_name="Header Image Alt Text",
                    ),
                ),
                (
                    "ministry_website",
                    models.CharField(
                        blank=True,
                        help_text="Website link for the individual ministry",
                        max_length=255,
                        null=True,
                        verbose_name="Ministry Website",
                    ),
                ),
                (
                    "first_section_header",
                    models.CharField(
                        blank=True,
                        help_text="Header text that will be shown in the section below the header",
                        max_length=255,
                        null=True,
                        verbose_name="First Section Header",
                    ),
                ),
                (
                    "first_section_content",
                    wagtail.core.fields.RichTextField(
                        blank=True,
                        help_text="Content text that will be shown in the section below the header",
                        null=True,
                        verbose_name="First Section Content",
                    ),
                ),
                (
                    "middle_section_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the middle section image of the page",
                        max_length=255,
                        null=True,
                        verbose_name="Middle Section Image Alt Text",
                    ),
                ),
                (
                    "description_header",
                    models.CharField(
                        blank=True,
                        help_text="Header of the description section of the page",
                        max_length=255,
                        null=True,
                        verbose_name="Description Header",
                    ),
                ),
                (
                    "description",
                    wagtail.core.fields.RichTextField(
                        blank=True,
                        help_text="Description section of the page",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Header image that is going to be displayed for the page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "middle_section_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that is going to be displayed in the middle section of the page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="InternationalMinistriesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "header_sub_title",
                    models.CharField(
                        blank=True,
                        help_text="Text that will be shown underneath of the title of the page",
                        max_length=255,
                        null=True,
                        verbose_name="Header Sub-title",
                    ),
                ),
                (
                    "header_bottom_text",
                    models.CharField(
                        blank=True,
                        help_text="Text that will be shwon at the bottom of the header portion of the page",
                        max_length=255,
                        null=True,
                        verbose_name="Header Bottom Text",
                    ),
                ),
                (
                    "header_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the header image of the page",
                        max_length=255,
                        null=True,
                        verbose_name="Header Image Alt Text",
                    ),
                ),
                (
                    "header_background_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the header background image of the page",
                        max_length=255,
                        null=True,
                        verbose_name="Header Image Alt Text",
                    ),
                ),
                (
                    "header_map_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the header map image of the page",
                        max_length=255,
                        null=True,
                        verbose_name="Header Map Image Alt Text",
                    ),
                ),
                (
                    "description_header",
                    models.CharField(
                        blank=True,
                        help_text="Header of the description section of the page",
                        max_length=255,
                        null=True,
                        verbose_name="Description Header",
                    ),
                ),
                (
                    "description",
                    wagtail.core.fields.RichTextField(
                        blank=True,
                        help_text="Description section of the page",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "areas_of_ministries_header",
                    models.CharField(
                        blank=True,
                        help_text="Text that will be shown as the header of the areas of ministries section of the page",
                        max_length=255,
                        null=True,
                        verbose_name="Description Header",
                    ),
                ),
                (
                    "giving_initiative_background_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the background image that is going to be displayed for giving initiative section of the page",
                        max_length=255,
                        null=True,
                        verbose_name="Header Map Image Alt Text",
                    ),
                ),
                (
                    "giving_initiative_title",
                    models.CharField(
                        blank=True,
                        help_text="The title for the giving initiative section",
                        max_length=100,
                        null=True,
                        verbose_name="Giving Initiative Title",
                    ),
                ),
                (
                    "giving_initiative_body",
                    models.TextField(
                        blank=True,
                        help_text="The text that will be shown under the giving initiative title",
                        null=True,
                        verbose_name="Giving Initiative Body",
                    ),
                ),
                (
                    "director_name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the director for the region",
                        max_length=100,
                        null=True,
                        verbose_name="Director Name",
                    ),
                ),
                (
                    "director_image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the director image",
                        max_length=100,
                        null=True,
                        verbose_name="Director Image Alt Text",
                    ),
                ),
                (
                    "director_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="The phone number of the director for the region",
                        max_length=225,
                        null=True,
                        verbose_name="Director Phone Number",
                    ),
                ),
                (
                    "director_website_link",
                    models.CharField(
                        blank=True,
                        help_text="The website link of the director",
                        max_length=225,
                        null=True,
                        verbose_name="Director Website Link",
                    ),
                ),
                (
                    "director_facebook_link",
                    models.CharField(
                        blank=True,
                        help_text="The Facebook link of the director",
                        max_length=225,
                        null=True,
                        verbose_name="Director Facebook Link",
                    ),
                ),
                (
                    "director_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image of the director for the region",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "giving_initiative_background_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Background image that is going to be displayed for giving initiative section of the page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "header_background_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Header background image that is going to be displayed for the page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Header image that is going to be displayed for the page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "header_map_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Header map image that is going to be displayed for the page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "individual_ministries",
                    models.ForeignKey(
                        blank=True,
                        help_text="Individual minitries section of the page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="international_ministries.IndividualMinistryPage",
                        verbose_name="Individual Ministries",
                    ),
                ),
                (
                    "stories_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Stories section of the page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stories.StoryIndexPage",
                        verbose_name="Stories Section",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
