# Generated by Django 2.2.28 on 2022-06-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_ministries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalministriespage',
            name='areas_of_ministries_header',
            field=models.CharField(blank=True, help_text='Text that will be shown as the header of the areas of ministries section of the page', max_length=255, null=True, verbose_name='Areas of Ministries Header'),
        ),
        migrations.AlterField(
            model_name='internationalministriespage',
            name='giving_initiative_background_image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the background image that is going to be displayed for giving initiative section of the page', max_length=255, null=True, verbose_name='Giving Initiative Background Image Alt Text'),
        ),
    ]
