# Generated by Django 2.2.28 on 2022-06-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_ministries', '0002_auto_20220610_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualministrypage',
            name='give_page_url',
            field=models.TextField(blank=True, help_text='URL of the give page for this specific individual ministry', null=True, verbose_name='Give Page URL'),
        ),
    ]
