# Generated by Django 2.2.28 on 2022-12-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_ministries', '0004_internationalministriespage_header_join_the_team_button_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalministriespage',
            name='director_phone_text',
            field=models.CharField(blank=True, help_text='The phone text beside the directors phone number.', max_length=225, null=True, verbose_name='Director Phone Text'),
        ),
        migrations.AddField(
            model_name='internationalministriespage',
            name='director_text',
            field=models.CharField(blank=True, help_text='The text above the directors name.', max_length=100, null=True, verbose_name='Director Text'),
        ),
        migrations.AddField(
            model_name='internationalministriespage',
            name='header_join_the_team_button_text',
            field=models.CharField(blank=True, help_text='Set the text for Join the team button', max_length=100, null=True, verbose_name='Join the team button text'),
        ),
        migrations.AddField(
            model_name='internationalministriespage',
            name='individual_ministries_readmore_button_text',
            field=models.CharField(blank=True, help_text='Read more button text at the end of each individual ministries in areas of ministries section.', max_length=255, null=True, verbose_name='Read More Button Text'),
        ),
        migrations.AddField(
            model_name='internationalministriespage',
            name='related_ministries_links_text',
            field=models.CharField(blank=True, help_text='Related ministries link text inside the directors section.', max_length=225, null=True, verbose_name='Related Ministries Link Text'),
        ),
        migrations.AddField(
            model_name='internationalministriespage',
            name='start_your_gift_today_button_text',
            field=models.TextField(blank=True, help_text='Text of the start your gift today button in the giving initiative section.', max_length=255, null=True, verbose_name='Start Your Gift Button Text'),
        ),
    ]
