# Generated by Django 2.2.28 on 2022-12-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_ministries', '0005_auto_20221212_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalministriespage',
            name='start_your_gift_today_button_text',
            field=models.CharField(blank=True, help_text='Text of the start your gift today button in the giving initiative section.', max_length=255, null=True, verbose_name='Start Your Gift Button Text'),
        ),
    ]
