# Generated by Django 2.2.27 on 2022-03-30 08:53

import json
from pathlib import Path

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


def add_contact_persons_initial_values(apps, schema_editor):
    path = Path(settings.BASE_DIR + "/cms/fixtures/contact_persons.json")

    with path.open() as data_file:
        json_file = json.load(data_file)

    ContactPerson = apps.get_model("cms", "ContactPerson")

    for contact_person in json_file:
        name = contact_person.get("fields").get("name")
        email_address = contact_person.get("fields").get("email_address")
        position = contact_person.get("fields").get("position")
        ContactPerson.objects.create(
            name=name, email_address=email_address, position=position
        )


def add_contact_information_initial_values(apps, schema_editor):
    path = Path(settings.BASE_DIR + "/cms/fixtures/contact_information.json")

    with path.open() as data_file:
        json_file = json.load(data_file)

    ContactInformation = apps.get_model("cms", "ContactInformation")
    ContactPerson = apps.get_model("cms", "ContactPerson")

    for contact_information in json_file:
        company_name = contact_information.get("fields").get("company_name")
        address1 = contact_information.get("fields").get("address1")
        address2 = contact_information.get("fields").get("address2")
        phone_number = contact_information.get("fields").get("phone_number")
        instance = ContactInformation.objects.create(
            company_name=company_name,
            address1=address1,
            address2=address2,
            phone_number=phone_number,
        )
        contact_persons = ContactPerson.objects.all()
        instance.contact_persons.set(contact_persons)
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("wagtailimages", "0023_add_choose_permissions"),
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Address"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Position"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Person",
                "verbose_name_plural": "Contact Persons",
            },
        ),
        migrations.CreateModel(
            name="GregMundisInitiative",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "message_section",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.core.blocks.CharBlock(
                                    form_classname="full title"
                                ),
                            ),
                            ("body", wagtail.core.blocks.TextBlock()),
                            ("video", wagtail.embeds.blocks.EmbedBlock()),
                        ]
                    ),
                ),
                (
                    "greg_mundis_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of Greg Mundis displayed",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "greg_mundis_position",
                    models.CharField(
                        blank=True,
                        help_text="Title of Greg Mundis displayed",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "greg_mundis_company",
                    models.CharField(
                        blank=True,
                        help_text="Company of Greg Mundis displayed",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "greg_mundis_description",
                    wagtail.core.fields.RichTextField(
                        blank=True,
                        help_text="Description under Greg Mundis name and title",
                        null=True,
                    ),
                ),
                (
                    "contact_info_title",
                    models.CharField(
                        blank=True,
                        help_text="Contact Info Title",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "greg_mundis_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Greg Mundis Image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ContactInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "address1",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Address 1"
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Address 2"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "contact_persons",
                    models.ManyToManyField(
                        related_name="contact_persons",
                        to="cms.ContactPerson",
                        verbose_name="Contact Persons",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Information",
                "verbose_name_plural": "Contact Information",
            },
        ),
        migrations.RunPython(
            add_contact_persons_initial_values, migrations.RunPython.noop
        ),
        migrations.RunPython(
            add_contact_information_initial_values, migrations.RunPython.noop
        ),
    ]
