# Generated by Django 2.2.28 on 2022-05-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20220405_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredresourcecenterproduct',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the image of the featured resource center product', max_length=100, null=True, verbose_name='Image Alt Text'),
        ),
        migrations.AddField(
            model_name='gregmundisinitiative',
            name='greg_mundis_image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the image of greg mundis', max_length=100, null=True, verbose_name='Greg Mundis Image Alt Text'),
        ),
    ]
