# Generated by Django 2.2.28 on 2022-05-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20220510_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.CharField(blank=True, help_text='Facebook URL link', max_length=255, null=True, verbose_name='Facebook URL')),
                ('vimeo_url', models.CharField(blank=True, help_text='Viemo URL link', max_length=255, null=True, verbose_name='Vimeo URL')),
                ('youtube_url', models.CharField(blank=True, help_text='Youtube URL link', max_length=255, null=True, verbose_name='Youtube URL')),
                ('instagram_url', models.CharField(blank=True, help_text='Instagram URL link', max_length=255, null=True, verbose_name='Instagram URL')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
    ]
