# Generated by Django 2.2.28 on 2022-05-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0001_initial'),
        ('stories', '0002_storypage_image_alt_text'),
        ('regions', '0001_initial'),
        ('cms', '0007_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='homepage',
            name='greg_mundis_section',
            field=models.ForeignKey(blank=True, help_text='Greg Mundis section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.GregMundisInitiative', verbose_name='Greg Mundis Section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='prayer_section',
            field=models.ForeignKey(blank=True, help_text='Prayer section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='prayers.PrayerPage', verbose_name='Prayer Section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='region_section',
            field=models.ForeignKey(blank=True, help_text='Region section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='regions.RegionIndexPage', verbose_name='Region Section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='story_section',
            field=models.ForeignKey(blank=True, help_text='Story section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stories.StoryIndexPage', verbose_name='Story Section'),
        ),
    ]
