# Generated by Django 2.2.28 on 2022-06-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20220607_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gregmundisinitiative',
            name='initiatives_section',
        ),
    ]
