# Generated by Django 2.2.28 on 2022-06-29 11:57

from django.db import migrations, models
import django.db.models.deletion
import home.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('cms', '0013_auto_20220610_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuStrategyPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_text', models.TextField(blank=True, help_text='Text that will be shown at the bottom of the page title', null=True, verbose_name='Bottom Text')),
                ('image', models.ImageField(blank=True, help_text='Image that will be shown for the page in the menu', null=True, upload_to=home.utils.get_upload_path, verbose_name='Image')),
                ('image_alt_text', models.CharField(blank=True, help_text='Alt text for the image', max_length=255, null=True, verbose_name='Image Alt Text')),
                ('page', models.ForeignKey(blank=True, help_text='Page that you want to show in the strategy tab in the menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Menu Strategy Page',
                'verbose_name_plural': 'Menu Strategy Page',
            },
        ),
        migrations.CreateModel(
            name='MenuResourcePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_text', models.TextField(blank=True, help_text='Text that will be shown at the bottom of the page title', null=True, verbose_name='Bottom Text')),
                ('image', models.ImageField(blank=True, help_text='Image that will be shown for the page in the menu', null=True, upload_to=home.utils.get_upload_path, verbose_name='Image')),
                ('image_alt_text', models.CharField(blank=True, help_text='Alt text for the image', max_length=255, null=True, verbose_name='Image Alt Text')),
                ('page', models.ForeignKey(blank=True, help_text='Page that you want to show in the resources tab in the menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Menu Resource Page',
                'verbose_name_plural': 'Menu Resource Pages',
            },
        ),
        migrations.CreateModel(
            name='MenuExplorePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_text', models.TextField(blank=True, help_text='Text that will be shown at the bottom of the page title', null=True, verbose_name='Bottom Text')),
                ('image', models.ImageField(blank=True, help_text='Image that will be shown for the page in the menu', null=True, upload_to=home.utils.get_upload_path, verbose_name='Image')),
                ('image_alt_text', models.CharField(blank=True, help_text='Alt text for the image', max_length=255, null=True, verbose_name='Image Alt Text')),
                ('page', models.ForeignKey(blank=True, help_text='Page that you want to show in the explore tab in the menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Menu Explore Page',
                'verbose_name_plural': 'Menu Explore Pages',
            },
        ),
    ]
