# Generated by Django 2.2.28 on 2022-07-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20220706_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Text that will be shown besides the missions', null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Mission Text',
                'verbose_name_plural': 'Mission Text',
            },
        ),
    ]
