# Generated by Django 2.2.28 on 2022-07-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20220711_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Area, Country, or Ministry name to be displayed', max_length=100, null=True, verbose_name='Text')),
                ('value', models.CharField(blank=True, help_text='Value of Area, Country, Ministry', max_length=100, null=True, verbose_name='Value')),
                ('type', models.CharField(choices=[('Area', 'Area'), ('Country', 'Country'), ('Ministry', 'Ministry')], help_text='Set the type as Area, Country, or Ministry)', max_length=50, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'CAM',
                'verbose_name_plural': 'CAM',
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, null=True, verbose_name='Company Name')),
                ('name', models.CharField(blank=True, help_text='Name of the contact person', max_length=50, null=True, verbose_name='Name')),
                ('email_address', models.EmailField(blank=True, help_text='Email address of the contact person', max_length=254, verbose_name='Email Address')),
                ('position', models.CharField(blank=True, help_text='Position of the contact person in the company', max_length=50, null=True, verbose_name='Position')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='is_main_region',
            field=models.BooleanField(default=False, help_text='Set this as true', null=True, verbose_name='Is Main Region'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_guid',
            field=models.CharField(blank=True, help_text='Set the RegionGUID', max_length=100, null=True, verbose_name='Region GUID'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='position',
            field=models.CharField(blank=True, help_text='Position of the person in the company', max_length=50, null=True, verbose_name='Position'),
        ),
    ]
