# Generated by Django 2.2.28 on 2022-07-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20220718_0636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInformation',
        ),
        migrations.AlterModelOptions(
            name='cam',
            options={'verbose_name': 'CAM', 'verbose_name_plural': 'CAMS'},
        ),
    ]
