# Generated by Django 2.2.28 on 2022-08-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20220721_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the district', max_length=100, null=True, verbose_name='Name')),
                ('number', models.CharField(blank=True, help_text='Value of the ', max_length=50, null=True, verbose_name='Number')),
            ],
            options={
                'verbose_name': 'Sending District',
                'verbose_name_plural': 'Sending Districts',
            },
        ),
    ]
