# Generated by Django 2.2.28 on 2022-08-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_sendingdistrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingdistrict',
            name='number',
            field=models.CharField(blank=True, help_text='Value of the district', max_length=50, null=True, verbose_name='Number'),
        ),
    ]
