# Generated by Django 2.2.28 on 2022-09-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20220815_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='prayer_button_one',
            field=models.CharField(blank=True, help_text='Set Prayer button text in the prayer section', max_length=255, null=True, verbose_name='Prayer Button One'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='prayer_button_one_url',
            field=models.CharField(blank=True, help_text='Set the URL for Prayer button one in the prayer section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='prayer_button_two',
            field=models.CharField(blank=True, help_text='Set Prayer button text in the prayer section', max_length=255, null=True, verbose_name='Prayer Button Two'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='prayer_button_two_url',
            field=models.CharField(blank=True, help_text='Set the URL for Prayer button two in the prayer section', max_length=255, null=True),
        ),
    ]
