# Generated by Django 2.2.28 on 2022-09-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20220902_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredresourcecenterproduct',
            options={'verbose_name': 'Featured Resource Center Product', 'verbose_name_plural': 'Featured Resource Center Products'},
        ),
    ]
