# Generated by Django 2.2.28 on 2022-09-22 06:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20220920_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='missiontext',
            options={'verbose_name': 'RPTS Section', 'verbose_name_plural': 'RPTS Section'},
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_text',
            field=modelcluster.fields.ParentalKey(blank=True, help_text='Set mission text for missions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_texts', to='cms.MissionText'),
        ),
        migrations.AddField(
            model_name='mission',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
