# Generated by Django 2.2.28 on 2022-09-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20220920_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='gregmundisinitiative',
            name='contact_person_email_address',
            field=models.EmailField(blank=True, help_text='Email address of the contact person', max_length=254, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='gregmundisinitiative',
            name='contact_person_name',
            field=models.CharField(blank=True, help_text='Name of the contact person', max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='gregmundisinitiative',
            name='contact_person_position',
            field=models.CharField(blank=True, help_text='Position of the person in the company', max_length=50, null=True, verbose_name='Position'),
        ),
    ]
