# Generated by Django 2.2.28 on 2022-09-23 03:08

from django.db import migrations, models
import django.db.models.deletion
import home.utils
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_auto_20220922_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='header_map_image',
            field=models.FileField(blank=True, help_text='Image that will be shown in the map portion in the header of the page', null=True, upload_to=home.utils.get_upload_path, verbose_name='Header Map Image'),
        ),
        migrations.AddField(
            model_name='region',
            name='header_map_image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the map image in the header of the page', max_length=100, null=True, verbose_name='Header Map Image Alt Text'),
        ),
        migrations.CreateModel(
            name='MissionaryRegionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('header_image', models.FileField(blank=True, help_text='Background image that will be shown in the header portion of the page', null=True, upload_to=home.utils.get_upload_path, verbose_name='Header Image')),
                ('header_image_alt_text', models.CharField(blank=True, help_text='Alt text for the header image', max_length=255, null=True, verbose_name='Header Image Alt Text')),
                ('region', modelcluster.fields.ParentalKey(help_text='Region assigned for the iamges', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_images', to='cms.Region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Missionary Region Image',
                'verbose_name_plural': 'Missionary Region Images',
            },
        ),
    ]
