# Generated by Django 2.2.28 on 2022-09-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_auto_20220923_0308'),
        ('cms', '0024_auto_20220921_0532'),
    ]

    operations = [
    ]
