# Generated by Django 2.2.28 on 2022-09-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_merge_20220929_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedResourceCenterProduct',
        ),
    ]
