# Generated by Django 2.2.28 on 2022-10-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_delete_featuredresourcecenterproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAutomationSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_tag_opening', models.TextField(blank=True, help_text='Header Tag Opening', null=True, verbose_name='AFTER opening <header> tag')),
                ('header_tag_closing', models.TextField(blank=True, help_text='Header Tag Closing', null=True, verbose_name='BEFORE closing <header> tag')),
                ('body_tag_opening', models.TextField(blank=True, help_text='Body Tag Opening', null=True, verbose_name='AFTER opening <body> tag')),
                ('body_tag_closing', models.TextField(blank=True, help_text='Body Tag Closing', null=True, verbose_name='BEFORE closing <body> tag')),
            ],
            options={
                'verbose_name': 'Marketing Automation System Page',
                'verbose_name_plural': 'Marketing Automation System Pages',
            },
        ),
    ]
