# Generated by Django 2.2.28 on 2022-10-06 14:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_auto_20221006_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionaryApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cam',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sendingdistrict',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='cam',
            name='type',
            field=models.CharField(choices=[('Area', 'Area'), ('Country', 'Country'), ('Ministry', 'Ministry')], help_text='Set the type as Area, Country, or Ministry', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='sendingdistrict',
            name='number',
            field=models.CharField(blank=True, help_text='Number of the district', max_length=50, null=True, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='cam',
            name='missionary_api',
            field=modelcluster.fields.ParentalKey(blank=True, help_text='CAMS', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cam_missionary_api', to='cms.MissionaryApi'),
        ),
        migrations.AddField(
            model_name='region',
            name='missionary_api',
            field=modelcluster.fields.ParentalKey(blank=True, help_text='Regions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_missionary_api', to='cms.MissionaryApi'),
        ),
        migrations.AddField(
            model_name='sendingdistrict',
            name='missionary_api',
            field=modelcluster.fields.ParentalKey(blank=True, help_text='Sending Districts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sending_district_missionary_api', to='cms.MissionaryApi'),
        ),
    ]
