# Generated by Django 2.2.28 on 2022-11-09 03:14

from django.db import migrations, models
import django.db.models.deletion
import home.utils
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_homepage_header_section_missions_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionaryregionimage',
            name='region',
            field=modelcluster.fields.ParentalKey(help_text='Region assigned for the images', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_images', to='cms.Region', verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='HomePageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('header_image', models.FileField(blank=True, help_text='Background image that will be shown in the header portion of the page', null=True, upload_to=home.utils.get_upload_path, verbose_name='Header Image')),
                ('header_image_alt_text', models.CharField(blank=True, help_text='Alt text for the header image', max_length=255, null=True, verbose_name='Header Image Alt Text')),
                ('home_page', modelcluster.fields.ParentalKey(help_text='Page assigned to images', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_images', to='cms.HomePage', verbose_name='Home Page Header Images')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
