# Generated by Django 2.2.28 on 2022-11-09 13:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_auto_20221109_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageMissionTextRotate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('header_section_rotate_text', models.TextField(help_text='Text that will rotate besides the Missions text', null=True, verbose_name='Text')),
                ('home_page_rotate_text', modelcluster.fields.ParentalKey(help_text='Text assigned to header section mission', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_rotate_texts', to='cms.HomePage', verbose_name='Home Page Rotate Text')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
