# Generated by Django 2.2.28 on 2022-11-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_contactusform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUsForm',
            new_name='ContactUsModel',
        ),
    ]
