# Generated by Django 2.2.28 on 2022-11-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_auto_20221115_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, help_text='Address 1 text in the footer section', max_length=255, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, help_text='Address 2 text in the footer section', max_length=255, null=True, verbose_name='Address 2')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number in the footer section', max_length=255, null=True, verbose_name='Phone Number')),
                ('are_you_called_button', models.CharField(blank=True, help_text='Are you called text in the footer section', max_length=255, null=True, verbose_name='Are you called button')),
                ('copyright_text', models.CharField(blank=True, help_text='Copyright text in the footer section', max_length=255, null=True, verbose_name='Copyright text')),
                ('home_section_button', models.CharField(blank=True, help_text='Home button in the footer section', max_length=255, null=True, verbose_name='Home button section')),
                ('home_section_prayer_button', models.CharField(blank=True, help_text='Phone number in the footer section', max_length=255, null=True, verbose_name='Prayer button')),
                ('home_section_give_button', models.CharField(blank=True, help_text='Give button in the footer section', max_length=255, null=True, verbose_name='Give button')),
                ('home_section_go_button', models.CharField(blank=True, help_text='Go button in the footer section', max_length=255, null=True, verbose_name='Go button')),
                ('home_section_about_us_button', models.CharField(blank=True, help_text='About Us button in the footer section', max_length=255, null=True, verbose_name='About Us')),
                ('home_section_executive_office_button', models.CharField(blank=True, help_text='Executive Office button in the footer section', max_length=255, null=True, verbose_name='Executive Office button')),
                ('home_section_privacy_permissions_button', models.CharField(blank=True, help_text='Privacy and Permissions button in the footer section', max_length=255, null=True, verbose_name='Privacy and Permissions button')),
                ('resources_section_button', models.CharField(blank=True, help_text='Resources Section button in the footer section', max_length=255, null=True, verbose_name='Resources Section button')),
                ('resources_section_stories_button', models.CharField(blank=True, help_text='Stories button in the footer section', max_length=255, null=True, verbose_name='Stories button')),
                ('resources_section_photos_button', models.CharField(blank=True, help_text='Photos button in the footer section', max_length=255, null=True, verbose_name='Photos button')),
                ('resources_section_videos_button', models.CharField(blank=True, help_text='Videos button in the footer section', max_length=255, null=True, verbose_name='Videos button')),
                ('resources_section_world_view_button', models.CharField(blank=True, help_text='WorldView & More button in the footer section', max_length=255, null=True, verbose_name='WorldView & More button')),
                ('resources_section_merchandise_button', models.CharField(blank=True, help_text='Stories button in the footer section', max_length=255, null=True, verbose_name='Merchandise button')),
                ('explore_section_button', models.CharField(blank=True, help_text='Explore section button in the footer section', max_length=255, null=True, verbose_name='Explore section button')),
                ('explore_section_africa_button', models.CharField(blank=True, help_text='Africa button in the footer section', max_length=255, null=True, verbose_name='Africa button')),
                ('explore_section_asia_pacific_button', models.CharField(blank=True, help_text='Asia Pacific button in the footer section', max_length=255, null=True, verbose_name='Asia Pacific button')),
                ('explore_section_eurasia_button', models.CharField(blank=True, help_text='Eurasia button in the footer section', max_length=255, null=True, verbose_name='Eurasia button')),
                ('explore_section_europe_button', models.CharField(blank=True, help_text='Europe button in the footer section', max_length=255, null=True, verbose_name='Europe button')),
                ('explore_section_latin_america_button', models.CharField(blank=True, help_text='Latin America button in the footer section', max_length=255, null=True, verbose_name='Latin America button')),
                ('explore_section_northern_asia_button', models.CharField(blank=True, help_text='Northern Asia button in the footer section', max_length=255, null=True, verbose_name='Northern Asia button')),
                ('explore_section_international_ministries_button', models.CharField(blank=True, help_text='International Ministries button in the footer section', max_length=255, null=True, verbose_name='International Ministries button')),
                ('strategy_section_button', models.CharField(blank=True, help_text='Strategy section  button in the footer section', max_length=255, null=True, verbose_name='Strategy section button')),
                ('strategy_section_reaching_button', models.CharField(blank=True, help_text='Reaching button in the footer section', max_length=255, null=True, verbose_name='Reaching button')),
                ('strategy_section_planting_button', models.CharField(blank=True, help_text='Planting button in the footer section', max_length=255, null=True, verbose_name='Planting button')),
                ('strategy_section_training_button', models.CharField(blank=True, help_text='Training button in the footer section', max_length=255, null=True, verbose_name='Training button')),
                ('strategy_section_serving_button', models.CharField(blank=True, help_text='Serving button in the footer section', max_length=255, null=True, verbose_name='Serving button')),
                ('connect_section_button', models.CharField(blank=True, help_text='Connect section button in the footer section', max_length=255, null=True, verbose_name='Connect section button')),
                ('connect_section_get_in_touch_button', models.CharField(blank=True, help_text='Get in touch button in the footer section', max_length=255, null=True, verbose_name='Get in touch button')),
            ],
            options={
                'verbose_name': 'Footer Section Button',
                'verbose_name_plural': 'Footer Section Buttons',
            },
        ),
    ]
