# Generated by Django 2.2.28 on 2022-11-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0039_auto_20221116_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerconnectcolumn',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='footerconnectcolumn',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='footerconnectcolumn',
            name='vimeo_url',
        ),
        migrations.RemoveField(
            model_name='footerconnectcolumn',
            name='youtube_url',
        ),
        migrations.AlterField(
            model_name='footerhomecolumn',
            name='is_top_link',
            field=models.BooleanField(default=False, help_text='Set this to True to make text bold and moved at the top of the column', null=True, verbose_name='Is Top text'),
        ),
    ]
