# Generated by Django 2.2.28 on 2022-11-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_auto_20221116_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerconnectcolumn',
            name='is_top_link',
            field=models.BooleanField(default=False, help_text='Check the box to set this to True and make text bold and moved at the top of the column', null=True, verbose_name='Is Top text'),
        ),
    ]
