# Generated by Django 2.2.28 on 2022-11-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_footerconnectcolumn_is_top_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuexplorepage',
            name='bottom_text_es',
            field=models.TextField(blank=True, help_text='Spanish text that will be shown at the bottom of the page title', null=True, verbose_name='Bottom Text in Spanish'),
        ),
        migrations.AddField(
            model_name='menuexplorepage',
            name='page_title_es',
            field=models.CharField(blank=True, help_text='Name of the page that will be displayed in spanish if you dont want the page name to display in the menu.', max_length=255, null=True, verbose_name='Page Title in Spanish'),
        ),
        migrations.AddField(
            model_name='menuresourcepage',
            name='bottom_text_es',
            field=models.TextField(blank=True, help_text='Spanish text that will be shown at the bottom of the page title', null=True, verbose_name='Bottom Text in Spanish'),
        ),
        migrations.AddField(
            model_name='menuresourcepage',
            name='page_title_es',
            field=models.CharField(blank=True, help_text='Name of the page that will be displayed in spanish if you dont want the page name to display in the menu.', max_length=255, null=True, verbose_name='Page Title in Spanish'),
        ),
        migrations.AddField(
            model_name='menustrategypage',
            name='bottom_text_es',
            field=models.TextField(blank=True, help_text='Spanish text that will be shown at the bottom of the page title', null=True, verbose_name='Bottom Text in Spanish'),
        ),
    ]
