# Generated by Django 2.2.28 on 2022-11-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_auto_20221123_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='all_resources_modal_button',
            field=models.CharField(blank=True, help_text='Set All resources button text in the menu modal', max_length=255, null=True, verbose_name='All Resources button text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='are_you_called_button_nav',
            field=models.CharField(blank=True, help_text='Set Are you called button text in the navbar section', max_length=255, null=True, verbose_name='Are you Called button text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='explore_tab_button',
            field=models.CharField(blank=True, help_text='Set Explore tab text in the menu modal', max_length=255, null=True, verbose_name='Explore tab text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='give_button',
            field=models.CharField(blank=True, help_text='Set Give button text in the home page', max_length=255, null=True, verbose_name='Give button text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='give_modal_button',
            field=models.CharField(blank=True, help_text='Set Give button text in the menu modal', max_length=255, null=True, verbose_name='Give button modal text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='go_button',
            field=models.CharField(blank=True, help_text='Set Go button text in the home page', max_length=255, null=True, verbose_name='Go button text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='go_modal_button',
            field=models.CharField(blank=True, help_text='Set Go button text in the menu modal', max_length=255, null=True, verbose_name='Go button modal text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_section_header_title',
            field=models.CharField(blank=True, help_text='Set mission section header title in the home page', max_length=255, null=True, verbose_name='Mission section header title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pray_button',
            field=models.CharField(blank=True, help_text='Set Pray button text in the home page', max_length=255, null=True, verbose_name='Pray button text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pray_modal_button',
            field=models.CharField(blank=True, help_text='Set Pray button text in the menu modal', max_length=255, null=True, verbose_name='Pray button modal text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='region_section_explore_button',
            field=models.CharField(blank=True, help_text='Set the Region section explore button in the home page', max_length=255, null=True, verbose_name='Region Section Explore Button'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='region_section_header_text',
            field=models.CharField(blank=True, help_text='Set the Region section header text in the home page', max_length=255, null=True, verbose_name='Region Section Header Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='region_section_map_view_text',
            field=models.CharField(blank=True, help_text='Set the Region section map view text in the home page', max_length=255, null=True, verbose_name='Region Section Map View Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='resources_tab_button',
            field=models.CharField(blank=True, help_text='Set Resources tab text in the menu modal', max_length=255, null=True, verbose_name='Resources tab text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='strategy_tab_button',
            field=models.CharField(blank=True, help_text='Set Resources tab text in the menu modal', max_length=255, null=True, verbose_name='Strategy tab text'),
        ),
        migrations.AddField(
            model_name='mission',
            name='name_es',
            field=models.CharField(blank=True, help_text='Name of the mission', max_length=100, null=True, verbose_name='Name in Spanish'),
        ),
        migrations.AddField(
            model_name='missiontext',
            name='text_es',
            field=models.TextField(help_text='Text that will be shown besides the missions', null=True, verbose_name='Text in Spanish'),
        ),
    ]
