# Generated by Django 2.2.28 on 2022-12-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_auto_20221128_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontext',
            name='our_mission_text',
            field=models.TextField(help_text='Our mission text above missions section.', null=True, verbose_name='Our Mission Text'),
        ),
        migrations.AddField(
            model_name='missiontext',
            name='our_mission_text_es',
            field=models.TextField(help_text='Our mission text above missions section.', null=True, verbose_name='Our Mission Text in Spanish'),
        ),
    ]
