# Generated by Django 2.2.28 on 2022-12-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0046_auto_20221207_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='initial_subheader_section_missions_text',
            field=models.CharField(blank=True, help_text='Set the initial subheader text under the missions header.', max_length=255, null=True, verbose_name='Initial Subheader Section Mission Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subheader_section_missions_text',
            field=models.CharField(blank=True, help_text='Set the subheader text under the missions header.', max_length=255, null=True, verbose_name='Subheader Section Mission Text'),
        ),
    ]
