# Generated by Django 2.2.28 on 2022-12-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0047_auto_20221213_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='email_button_pill_text',
            field=models.CharField(blank=True, help_text='Set Email Button Pill text in notifications settings modal', max_length=255, null=True, verbose_name='Email Button Pill text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='giving_initiatives_notification_header_text',
            field=models.CharField(blank=True, help_text='Set Giving Initiatives Notification Header text in notifications settings modal', max_length=255, null=True, verbose_name='Giving Initiatives Notification Header text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='giving_initiatives_notification_sub_text',
            field=models.CharField(blank=True, help_text='Set Giving Initiatives Notification Sub text in notifications settings modal', max_length=255, null=True, verbose_name='Giving Initiatives Notification Sub text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='notification_settings_column_text',
            field=models.CharField(blank=True, help_text='Set notification settings column text in notifications settings modal', max_length=255, null=True, verbose_name='Notification Settings column text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='notification_settings_side_text',
            field=models.CharField(blank=True, help_text='Set notification settings side text in notifications settings modal', max_length=255, null=True, verbose_name='Notification Settings side text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='prayer_notification_header_text',
            field=models.CharField(blank=True, help_text='Set Prayer Notification Header text in notifications settings modal', max_length=255, null=True, verbose_name='Prayer Notification Header text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='prayer_notification_sub_text',
            field=models.CharField(blank=True, help_text='Set Prayer Notification Sub text in notifications settings modal', max_length=255, null=True, verbose_name='Prayer Notification Sub text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quick_pages_text',
            field=models.CharField(blank=True, help_text='Set quick pages text in notifications settings modal', max_length=255, null=True, verbose_name='Quick Pages section text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stories_notification_header_text',
            field=models.CharField(blank=True, help_text='Set Stories Notification Header text in notifications settings modal', max_length=255, null=True, verbose_name='Stories Notification Header text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stories_notification_sub_text',
            field=models.CharField(blank=True, help_text='Set Stories Notification Sub text in notifications settings modal', max_length=255, null=True, verbose_name='Stories Notification Sub text'),
        ),
    ]
