# Generated by Django 2.2.28 on 2022-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0048_auto_20221214_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='prayer_section_background_color',
            field=models.CharField(blank=True, help_text='Hex Code Color that will be shown in the prayer section. Example: #8155BA', max_length=255, null=True, verbose_name='Prayer Section Background Color'),
        ),
    ]
