# Generated by Django 2.2.28 on 2022-12-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0049_homepage_prayer_section_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='search_result_page_empty_query_text',
            field=models.CharField(blank=True, help_text='Set search result for text text in search result page.', max_length=255, null=True, verbose_name='Search Result Page Empty Query Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_result_page_input_placeholder',
            field=models.CharField(blank=True, help_text='Set placeholder text for search input in search result page.', max_length=255, null=True, verbose_name='Search Result Page Input Placeholder'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_result_page_no_result_found_text',
            field=models.CharField(blank=True, help_text='Text displayed when there are no matching query results.', max_length=255, null=True, verbose_name='Search Result Page No Result Found Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_result_page_search_button_text',
            field=models.CharField(blank=True, help_text='Set search button text text in search result page.', max_length=255, null=True, verbose_name='Search Result Page Search Button Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_result_page_search_result_for_text',
            field=models.CharField(blank=True, help_text='Set search result for text text in search result page.', max_length=255, null=True, verbose_name='Search Result Page Search Result For Text'),
        ),
    ]
