# Generated by Django 2.2.28 on 2022-12-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0050_auto_20221222_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='login_modal_header',
            field=models.CharField(blank=True, help_text='Set the text of the login modal header', max_length=255, null=True, verbose_name='Login Modal Header'),
        ),
    ]
