# Generated by Django 2.2.28 on 2022-07-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0002_auto_20220603_0410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prayer',
        ),
        migrations.DeleteModel(
            name='SocialPrayerFeed',
        ),
    ]
