# Generated by Django 2.2.28 on 2022-07-08 08:22

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('prayers', '0003_auto_20220708_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, help_text='Name of the prayer.', max_length=100, null=True, verbose_name='Name')),
                ('body', models.TextField(blank=True, help_text='Body of the prayer.', null=True, verbose_name='Body')),
                ('image_alt_text', models.CharField(blank=True, help_text='Alt text for the image of the prayer', max_length=100, null=True, verbose_name='Image Alt Text')),
                ('image', models.ForeignKey(blank=True, help_text='Image of the prayer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to='prayers.PrayerPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
