# Generated by Django 2.2.28 on 2022-09-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0004_prayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='image_alt_text',
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='name',
        ),
    ]
