# Generated by Django 2.2.28 on 2022-09-16 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('prayers', '0005_auto_20220902_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayer',
            options={'verbose_name': 'Prayer', 'verbose_name_plural': 'Prayers'},
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='page',
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='prayerpage',
            name='header_body',
        ),
        migrations.RemoveField(
            model_name='prayerpage',
            name='header_title',
        ),
        migrations.AddField(
            model_name='prayer',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Image of the prayer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the image of the prayer', max_length=100, null=True, verbose_name='Image Alt Text'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='is_featured_prayer',
            field=models.BooleanField(default=False, help_text='Set this to Yes if prayer is to be featured', null=True, verbose_name='Is Featured Prayer'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the prayer', max_length=100, null=True, verbose_name='Prayer Name'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='show_image',
            field=models.BooleanField(default=False, help_text='Set this to Yes to show image of the prayer', null=True, verbose_name='Show Image'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='pray_band_title',
            field=models.CharField(blank=True, help_text='Text in the title of the pray band portion of the prayer page.', max_length=100, null=True, verbose_name='Pray Band Title'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='pray_header_body',
            field=models.TextField(blank=True, help_text='Body for the header description portion of the prayer page.', null=True, verbose_name='Prayer Header Description'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='pray_header_title',
            field=models.CharField(blank=True, help_text='Title for the header title portion of the prayer page.', max_length=100, null=True, verbose_name='Prayer Header Title'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='body',
            field=models.TextField(blank=True, help_text='Body of the prayer', null=True, verbose_name='Body'),
        ),
    ]
