# Generated by Django 2.2.28 on 2022-09-16 11:04

from django.db import migrations, models
import home.utils


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0006_auto_20220916_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the prayer', null=True, upload_to=home.utils.get_upload_path, verbose_name='Image'),
        ),
    ]
