# Generated by Django 2.2.28 on 2022-11-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0007_auto_20220916_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='body_es',
            field=models.TextField(blank=True, help_text='Body of the prayer', null=True, verbose_name='Body of the Prayer in Spanish'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='name_es',
            field=models.CharField(blank=True, help_text='Name of the prayer', max_length=100, null=True, verbose_name='Prayer Name in Spanish'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='last_section_facebook_button',
            field=models.CharField(blank=True, help_text='Text of the Last Section Facebook Button', max_length=100, null=True, verbose_name='Last Section Facebook Button'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='last_section_header_title',
            field=models.CharField(blank=True, help_text='Text of the Last Section Header Title', max_length=200, null=True, verbose_name='Last Section Header Title'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='last_section_instagram_button',
            field=models.CharField(blank=True, help_text='Text of the Last Section Instagram Button', max_length=100, null=True, verbose_name='Last Section Instagram Button'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='prayer_modal_header_title',
            field=models.CharField(blank=True, help_text='Text of the Prayer Modal Header Title', max_length=100, null=True, verbose_name='Prayer Modal Header Title'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='social_prayer_feed_card_description',
            field=models.TextField(blank=True, help_text='Text of the Social Prayer feed card description', null=True, verbose_name='Social Prayer Feed Section Description'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='social_prayer_feed_card_title',
            field=models.CharField(blank=True, help_text='Text of the Social Prayer feed card title', max_length=100, null=True, verbose_name='Social Prayer Feed Card Title'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='social_prayer_feed_modal_body',
            field=models.TextField(blank=True, help_text='Text of the Social Prayer feed Modal Body', null=True, verbose_name='Social Prayer Feed Modal Body'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='social_prayer_feed_modal_button',
            field=models.CharField(blank=True, help_text='Text of the Social Prayer feed modal button', max_length=200, null=True, verbose_name='Social Prayer Feed Modal Button'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='social_prayer_feed_modal_header_description',
            field=models.CharField(blank=True, help_text='Text of the Social Prayer feed modal header description', max_length=200, null=True, verbose_name='Social Prayer Feed Modal Header Description'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='social_prayer_feed_modal_sub_title',
            field=models.CharField(blank=True, help_text='Text of the Social Prayer feed modal sub title', max_length=200, null=True, verbose_name='Social Prayer Feed Modal Sub Title'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='social_prayer_feed_modal_title',
            field=models.CharField(blank=True, help_text='Text of the Social Prayer feed modal title', max_length=200, null=True, verbose_name='Social Prayer Feed Modal Title'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='social_prayer_feed_section_description',
            field=models.CharField(blank=True, help_text='Text of the Social Prayer Feed Section Description', max_length=100, null=True, verbose_name='Social Prayer Feed Section Description'),
        ),
        migrations.AddField(
            model_name='prayerpage',
            name='social_prayer_feed_section_title',
            field=models.CharField(blank=True, help_text='Text of the Social Prayer Feed Section Title', max_length=100, null=True, verbose_name='Social Prayer Feed Section Title'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='body',
            field=models.TextField(blank=True, help_text='Body of the prayer', null=True, verbose_name='Body of the Prayer'),
        ),
    ]
