# Generated by Django 2.2.28 on 2022-12-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0009_prayerpage_last_section_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayerpage',
            name='social_prayer_feed_modal_button',
        ),
    ]
