# Generated by Django 2.2.28 on 2022-12-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_missionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='findamissionarypage',
            name='all_areas_countries_ministries_dropdown_text',
            field=models.CharField(blank=True, help_text='Text of the all areas, countries, and ministries dropdown tab.', max_length=255, null=True, verbose_name='All Areas, Countries, and Ministries Dropdown Text'),
        ),
        migrations.AddField(
            model_name='findamissionarypage',
            name='all_region_dropdown_text',
            field=models.CharField(blank=True, help_text='Text of the all region dropdown tab.', max_length=255, null=True, verbose_name='All Region Dropdown Text'),
        ),
        migrations.AddField(
            model_name='findamissionarypage',
            name='all_sending_districts_dropdown_text',
            field=models.CharField(blank=True, help_text='Text of the all sending distrcits dropdown tab.', max_length=255, null=True, verbose_name='All Sending Districts Dropdown Text'),
        ),
        migrations.AddField(
            model_name='findamissionarypage',
            name='areas_dropdown_text',
            field=models.CharField(blank=True, help_text='Text of the areas dropdown option in areas, countries, and ministries dropdown tab.', max_length=255, null=True, verbose_name='Areas Dropdown Text'),
        ),
        migrations.AddField(
            model_name='findamissionarypage',
            name='countries_dropdown_text',
            field=models.CharField(blank=True, help_text='Text of the countries dropdown option in areas, countries, and ministries dropdown tab.', max_length=255, null=True, verbose_name='Countries Dropdown Text'),
        ),
        migrations.AddField(
            model_name='findamissionarypage',
            name='header_text',
            field=models.CharField(blank=True, help_text='Header text that is going to be displayed in the center of header image.', max_length=255, null=True, verbose_name='Header Text'),
        ),
        migrations.AddField(
            model_name='findamissionarypage',
            name='ministries_dropdown_text',
            field=models.CharField(blank=True, help_text='Text of the ministries dropdown option in areas, countries, and ministries dropdown tab.', max_length=255, null=True, verbose_name='Ministries Dropdown Text'),
        ),
        migrations.AddField(
            model_name='findamissionarypage',
            name='search_button_text',
            field=models.CharField(blank=True, help_text='Text of the search button.', max_length=255, null=True, verbose_name='Search Button Text'),
        ),
        migrations.AddField(
            model_name='findamissionarypage',
            name='search_input_placeholder_text',
            field=models.CharField(blank=True, help_text='Placeholder text of the search input.', max_length=255, null=True, verbose_name='Seach Input Placeholder Text'),
        ),
    ]
