# Generated by Django 2.2.28 on 2022-06-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('individual_missionaries', '0001_initial'),
        ('legacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header_image_alt_text', models.CharField(blank=True, help_text='Alt text for the header image', max_length=100, null=True, verbose_name='Header Image Alt Text')),
                ('header_side_text', models.CharField(blank=True, help_text='Text that will be shown on the left side of the header of the page', max_length=255, null=True, verbose_name='Header Side Text')),
                ('header_title_text', models.CharField(blank=True, help_text="Text of the title that will be shown on the right side of the header. Example ('Live Dead Africa')", max_length=255, null=True, verbose_name='Header Title Text')),
                ('header_title_description', models.TextField(blank=True, help_text='Text that will be shown below the header title text', null=True, verbose_name='Header Title Description')),
                ('first_section_image_alt_text', models.CharField(blank=True, help_text='Alt text for the first section image', max_length=255, null=True, verbose_name='First Section Image Alt Text')),
                ('first_section_title', models.CharField(blank=True, help_text="Text that will be shown in the first section of the page. Example 'Find a Missionary'", max_length=255, null=True, verbose_name='First Section Title')),
                ('initiatives_background_image_alt_text', models.CharField(blank=True, help_text='Alt text for the initiatives background image', max_length=255, null=True, verbose_name='Initiatives Background Image Alt Text')),
                ('second_section_image_alt_text', models.CharField(blank=True, help_text='Alt text for the second section image', max_length=255, null=True, verbose_name='Section Section Image Alt Text')),
                ('legacy_giving_image_alt_text', models.CharField(blank=True, help_text='Alt text for the legacy giving image', max_length=255, null=True, verbose_name='Legacy Giving Image Alt Text')),
                ('giving_faq_image_alt_text', models.CharField(blank=True, help_text='Alt text for the giving faq image', max_length=255, null=True, verbose_name='Giving FAQ Image Alt Text')),
                ('first_section_image', models.ForeignKey(blank=True, help_text="Image that will be shown in the first section or the 'Find a Missionary' portion of the page", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('giving_faq_image', models.ForeignKey(blank=True, help_text='Image that will be shown for the giving faq section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('header_image', models.ForeignKey(blank=True, help_text='Image that will be shown in the header portion of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('initiatives_background_image', models.ForeignKey(blank=True, help_text='Background Image that will be shown in the initiatives section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('legacy_giving_image', models.ForeignKey(blank=True, help_text='Image that will be shown for the legacy giving section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('legacy_giving_page', models.ForeignKey(blank=True, help_text='Legacy Giving page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='legacy.LegacyPage', verbose_name='Legacy Giving Page')),
                ('missionary_page', models.ForeignKey(blank=True, help_text='Individual Missionary page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='individual_missionaries.IndividualMissionaryIndexPage', verbose_name='Missionary Page')),
                ('second_section_image', models.ForeignKey(blank=True, help_text="Image that will be shown in the second section or the 'Senders Fund' portion of the page", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
