# Generated by Django 2.2.28 on 2022-06-06 13:26

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('individual_missionaries', '0001_initial'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('give', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialGivingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header_image_alt_text', models.CharField(blank=True, help_text='Alt text for the header image', max_length=255, null=True, verbose_name='Header Image Alt Text')),
                ('header_title_text', models.CharField(blank=True, help_text="Text of the title that will be shown on the header. Example ('Disaster Relief')", max_length=255, null=True, verbose_name='Header Title Text')),
                ('header_title_description', models.TextField(blank=True, help_text='Text that will be shown below the header title text', null=True, verbose_name='Header Title Description')),
                ('first_section_title', models.CharField(blank=True, help_text="Title of the first content section of the page. Example 'AGWM Responds to double disasters on two continents'", max_length=255, null=True, verbose_name='First Section Title')),
                ('first_section_content', models.TextField(blank=True, help_text='Content under the first section title.', null=True, verbose_name='First Section Content')),
                ('first_section_video_url', models.TextField(blank=True, help_text='URL of the video to be shown on the first section of the page. This needs to be the EMBED url of the video or else it will not work properly', null=True, verbose_name='First Section Video URL')),
                ('first_section_video_thumbnail_alt_text', models.CharField(blank=True, help_text='Alt text for the thumbnail of the first section video', max_length=255, null=True, verbose_name='First Section Video Thumbnail Alt Text')),
                ('give_section_image_alt_text', models.CharField(blank=True, help_text='Alt text for the give section image', max_length=255, null=True, verbose_name='First Section Video Thumbnail Alt Text')),
                ('give_section_title', models.CharField(blank=True, help_text='Title that will be shown in the give section of the page', max_length=255, null=True, verbose_name='Give Section Title')),
                ('give_section_content', models.TextField(blank=True, help_text='Text that will be shown as content under the give section title', null=True, verbose_name='Give Section Content')),
                ('second_section_title', models.CharField(blank=True, help_text="Title that will be shown in the second content section of the page. Example 'AGWM Responds to double disasters on two continents'", max_length=255, null=True, verbose_name='Second Section Title')),
                ('second_section_content', wagtail.core.fields.RichTextField(blank=True, help_text='Content that will be shown under the second section title', null=True, verbose_name='Second Section Content')),
                ('giving_link_url', models.TextField(blank=True, help_text='Giving Link URL for the specific dedicated giving page', null=True, verbose_name='Giving Link URL')),
                ('first_section_video_thumbnail', models.ForeignKey(blank=True, help_text='Image shown as the thumbnail of the first section video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('give_section_image', models.ForeignKey(blank=True, help_text='Image shown as the image for the give section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('header_image', models.ForeignKey(blank=True, help_text='Image that will be shown in the header portion of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('missionary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_giving_pages', to='individual_missionaries.Missionary', verbose_name='Missionary')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SpecialGivingPageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image_alt_text', models.CharField(blank=True, help_text='Alt text for the image', max_length=255, null=True, verbose_name='Image Alt Text')),
                ('image', models.ForeignKey(blank=True, help_text='Image of the special giving page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_giving_page_images', to='give.SpecialGivingPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
