# Generated by Django 2.2.28 on 2022-06-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0002_specialgivingpage_specialgivingpagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='givepage',
            name='second_section_dedicated_page',
            field=models.ForeignKey(blank=True, help_text='Dedicated page or special giving page of the second section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='give.SpecialGivingPage', verbose_name='Second Section Dedicated Page'),
        ),
    ]
