# Generated by Django 2.2.28 on 2022-06-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('give', '0003_givepage_second_section_dedicated_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='givepage',
            name='initiatives_content',
            field=models.TextField(blank=True, help_text='Content that will be under the initiatives title', null=True, verbose_name='Initiatives Content'),
        ),
        migrations.AddField(
            model_name='givepage',
            name='initiatives_title',
            field=models.CharField(blank=True, help_text='Title text that will be shown in the initiatives section of the page', max_length=255, null=True, verbose_name='Initiatives Title'),
        ),
        migrations.CreateModel(
            name='SpecialGivingIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header_image_alt_text', models.CharField(blank=True, help_text='Alt text for the header image', max_length=100, null=True, verbose_name='Header Image Alt Text')),
                ('header_image', models.ForeignKey(blank=True, help_text='Image that will be shown in the header portion of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
