# Generated by Django 2.2.28 on 2022-06-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('give', '0004_auto_20220609_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialgivingpage',
            name='give_section_image',
        ),
        migrations.RemoveField(
            model_name='specialgivingpage',
            name='give_section_image_alt_text',
        ),
        migrations.AddField(
            model_name='givepage',
            name='special_give_index_page',
            field=models.ForeignKey(blank=True, help_text='Special Giving Index Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='give.SpecialGivingIndexPage', verbose_name='Special Giving Index Page'),
        ),
        migrations.AddField(
            model_name='specialgivingpage',
            name='give_section_background_image',
            field=models.ForeignKey(blank=True, help_text='Image shown as the background image for the give section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='specialgivingpage',
            name='give_section_background_image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the give section background image', max_length=255, null=True, verbose_name='Give Section Background Image Alt Text'),
        ),
        migrations.AddField(
            model_name='specialgivingpage',
            name='give_section_icon_image',
            field=models.ForeignKey(blank=True, help_text='Image shown as the icon image for the give section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='specialgivingpage',
            name='give_section_icon_image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the give section icon image', max_length=255, null=True, verbose_name='Give Section Icon Image Alt Text'),
        ),
    ]
