# Generated by Django 2.2.28 on 2022-06-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0005_auto_20220609_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialgivingpage',
            name='first_section_video_thumbnail',
        ),
        migrations.RemoveField(
            model_name='specialgivingpage',
            name='first_section_video_thumbnail_alt_text',
        ),
        migrations.RemoveField(
            model_name='specialgivingpage',
            name='first_section_video_url',
        ),
        migrations.AddField(
            model_name='specialgivingpagegallery',
            name='is_video',
            field=models.BooleanField(default=False, help_text='Set this as true if the item in the gallery is a Video', verbose_name='Is Video'),
        ),
        migrations.AddField(
            model_name='specialgivingpagegallery',
            name='video_url',
            field=models.TextField(blank=True, help_text='URL of the video to be shown. This needs to be the EMBED url of the video or else it will not work properly', null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='specialgivingpagegallery',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Image of the special giving page. This also serves as the thumbnail if the item of the gallery is a video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
