# Generated by Django 2.2.28 on 2022-06-15 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('faq', '0001_initial'),
        ('give', '0006_auto_20220613_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialgivingpage',
            name='missionary',
        ),
        migrations.AddField(
            model_name='givepage',
            name='giving_faq_page',
            field=models.ForeignKey(blank=True, help_text='Give FAQ Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='faq.FaqPage'),
        ),
        migrations.AddField(
            model_name='specialgivingpage',
            name='page_type',
            field=models.CharField(choices=[('regional', 'Regional'), ('general', 'General'), ('executive', 'Executive'), ('special', 'Special')], help_text='Type of the Special Give Page/Dedicated Project', max_length=100, null=True, verbose_name='Page Type'),
        ),
        migrations.AddField(
            model_name='specialgivingpage',
            name='thumbnail_image',
            field=models.ForeignKey(blank=True, help_text='Image that will be shown as the thumbnail in the slider of the give page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='specialgivingpage',
            name='thumbnail_image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the thumbnail image', max_length=255, null=True, verbose_name='Header Image Alt Text'),
        ),
    ]
