# Generated by Django 2.2.28 on 2022-09-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0007_auto_20220615_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialgivingpage',
            options={'verbose_name': 'Giving Initiative', 'verbose_name_plural': 'Giving Initiatives'},
        ),
    ]
