# Generated by Django 2.2.28 on 2022-09-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0008_auto_20220920_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialgivingpage',
            options={'verbose_name': 'Type of Giving Initiative', 'verbose_name_plural': 'Type of Giving Initiatives'},
        ),
    ]
