# Generated by Django 2.2.28 on 2022-10-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0009_auto_20220920_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialgivingpage',
            options={'verbose_name': 'Giving Initiative', 'verbose_name_plural': 'Giving Initiatives'},
        ),
        migrations.AlterField(
            model_name='specialgivingpage',
            name='page_type',
            field=models.CharField(choices=[('regional', 'Regional'), ('general', 'General'), ('executive', 'Executive'), ('special', 'Special')], help_text='Type of Giving Initiatives', max_length=100, null=True, verbose_name='Page Type'),
        ),
    ]
