# Generated by Django 2.2.28 on 2022-10-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0010_auto_20221006_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givepage',
            name='initiatives_content',
        ),
        migrations.RemoveField(
            model_name='givepage',
            name='initiatives_title',
        ),
        migrations.AddField(
            model_name='givepage',
            name='slider_header_text',
            field=models.CharField(blank=True, help_text='Header text for the giving initiative slider section', max_length=255, null=True, verbose_name='Slider Header'),
        ),
    ]
