# Generated by Django 2.2.28 on 2022-11-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0011_auto_20221013_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='givepage',
            name='disaster_relief_slider_give_now_button',
            field=models.CharField(blank=True, help_text='Set the text for Give Now button', max_length=255, null=True, verbose_name='Give Now Button Text in Disaster Relief Section'),
        ),
        migrations.AddField(
            model_name='givepage',
            name='disaster_relief_slider_learn_more_button',
            field=models.CharField(blank=True, help_text='Set the text for Learn More button', max_length=255, null=True, verbose_name='Learn More Button Text in Disaster Relief Section'),
        ),
        migrations.AddField(
            model_name='givepage',
            name='executive_initiatives_button',
            field=models.CharField(blank=True, help_text='Set the text for Executive Initiatives button', max_length=255, null=True, verbose_name='Executive Initiatives Button Text'),
        ),
        migrations.AddField(
            model_name='givepage',
            name='give_to_missionary_button',
            field=models.CharField(blank=True, help_text='Set the text for Give to a Missionary button', max_length=255, null=True, verbose_name='Give to a Missionary Button Text'),
        ),
        migrations.AddField(
            model_name='givepage',
            name='giving_faq_button',
            field=models.CharField(blank=True, help_text='Set the text for Giving FAQ button', max_length=255, null=True, verbose_name='Giving FAQ Button Text'),
        ),
        migrations.AddField(
            model_name='givepage',
            name='giving_initiatives_slider_give_now_button',
            field=models.CharField(blank=True, help_text='Set the text for Give Now button', max_length=255, null=True, verbose_name='Give Now Button Text'),
        ),
        migrations.AddField(
            model_name='givepage',
            name='giving_initiatives_slider_learn_more_button',
            field=models.CharField(blank=True, help_text='Set the text for Learn More button', max_length=255, null=True, verbose_name='Learn More Button Text'),
        ),
        migrations.AddField(
            model_name='givepage',
            name='giving_initiatives_slider_view_all_button',
            field=models.CharField(blank=True, help_text='Set the text for View All button', max_length=255, null=True, verbose_name='View All Button Text'),
        ),
        migrations.AddField(
            model_name='givepage',
            name='legacy_giving_button',
            field=models.CharField(blank=True, help_text='Set the text for Legacy Giving button', max_length=255, null=True, verbose_name='Legacy Giving Button Text'),
        ),
        migrations.AddField(
            model_name='givepage',
            name='list_of_missionary_button',
            field=models.CharField(blank=True, help_text='Set the text for List of Missionaries button', max_length=255, null=True, verbose_name='List of Missionaries Button Text'),
        ),
    ]
