# Generated by Django 2.2.28 on 2022-12-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0012_auto_20221125_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='givepage',
            name='is_legacy_page_external',
            field=models.BooleanField(default=False, help_text='Checkbox for determining whether the Legacy Giving button is an external page or not', verbose_name='Is Legacy Page External'),
        ),
        migrations.AddField(
            model_name='givepage',
            name='legacy_giving_external_url',
            field=models.CharField(blank=True, help_text='URL for cases where the Legacy Page is external', max_length=255, null=True, verbose_name='Legacy Giving External URL'),
        ),
    ]
