# Generated by Django 2.2.28 on 2022-05-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storypage",
            name="image_alt_text",
            field=models.CharField(
                blank=True,
                help_text="Alt text for the image",
                max_length=100,
                null=True,
                verbose_name="Image Alt Text",
            ),
        ),
    ]
