# Generated by Django 2.2.28 on 2022-05-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_storypage_image_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='simple_prayer',
            field=models.TextField(blank=True, help_text="Prayer that will be displayed under the 'Todays simple prayer'", null=True, verbose_name='Simple Prayer'),
        ),
    ]
