# Generated by Django 2.2.28 on 2022-06-15 16:03

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20220603_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypage',
            name='simple_prayer',
            field=wagtail.core.fields.RichTextField(blank=True, help_text="Prayer that will be displayed under the 'Todays simple prayer'", null=True, verbose_name='Simple Prayer'),
        ),
    ]
