# Generated by Django 2.2.28 on 2022-12-06 09:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20220615_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorySliderHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('slider_header_text', models.CharField(blank=True, help_text='Header text above stories slider.', max_length=255, null=True, verbose_name='Story Slider Header Text')),
                ('slider_header_text_es', models.CharField(blank=True, help_text='Header text above stories slider in Spanish page.', max_length=255, null=True, verbose_name='Story Slider Header Text in Spanish')),
                ('slider_subheader_text', models.CharField(blank=True, help_text='Subheader text above stories slider.', max_length=255, null=True, verbose_name='Story Slider Subheader Text')),
                ('slider_subheader_text_es', models.CharField(blank=True, help_text='Subheader text above stories slider in Spanish.', max_length=255, null=True, verbose_name='Story Slider Subheader Text in Spanish')),
                ('slider_header_read_all_button', models.CharField(blank=True, help_text='Button text above stories slider.', max_length=255, null=True, verbose_name='Story Slider Button Text')),
                ('slider_header_read_all_button_es', models.CharField(blank=True, help_text='Button text above stories slider in Spanish.', max_length=255, null=True, verbose_name='Story Slider Button Text in Spanish')),
                ('story_slider', modelcluster.fields.ParentalKey(help_text='Page assigned to header text.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_slider_headers', to='stories.StoryIndexPage', verbose_name='Story Slider Header')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
