# Generated by Django 2.2.28 on 2022-12-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_auto_20221214_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyindexpage',
            name='story_slider_read_more_text',
            field=models.CharField(blank=True, help_text='Read more text for each story in story slider.', max_length=255, null=True, verbose_name='Story Pages Read More Text'),
        ),
    ]
