# Generated by Django 2.2.28 on 2022-09-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_view', '0004_auto_20220610_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldviewpage',
            name='name',
        ),
    ]
