# Generated by Django 2.2.28 on 2022-11-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_view', '0005_remove_worldviewpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldviewpage',
            name='world_view_url',
            field=models.CharField(blank=True, help_text='Set the URL for World Views', max_length=255, null=True, verbose_name='World View URL'),
        ),
    ]
