# Generated by Django 2.2.28 on 2022-12-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_view', '0006_worldviewpage_world_view_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldviewindexpage',
            name='search_button_text',
            field=models.CharField(blank=True, help_text='Text of the search button.', max_length=255, null=True, verbose_name='Search Button Text'),
        ),
        migrations.AddField(
            model_name='worldviewindexpage',
            name='search_input_placeholder',
            field=models.CharField(blank=True, help_text='Placeholder text for search input.', max_length=255, null=True, verbose_name='Search Input Placeholder Text'),
        ),
    ]
