# Generated by Django 2.2.27 on 2022-04-25 11:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionaryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('introduction', models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Introduction')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MissionaryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(blank=True, help_text='Name of missionary', max_length=100, null=True, verbose_name='Name')),
                ('location', models.CharField(blank=True, help_text='Location of the missionary', max_length=100, null=True, verbose_name='Location')),
                ('account_number', models.CharField(blank=True, help_text='Account number of the missionary', max_length=100, null=True, verbose_name='Account Number')),
                ('email_address', models.EmailField(blank=True, help_text='Email address of the missionary', max_length=100, null=True, verbose_name='Email Address')),
                ('website', models.CharField(blank=True, help_text='Website of the missionary', max_length=100, null=True, verbose_name='Website')),
                ('facebook_url', models.CharField(blank=True, help_text='Facebook URL of the missionary', max_length=100, null=True, verbose_name='Facebook URL')),
                ('instagram_url', models.CharField(blank=True, help_text='Instagram URL of the missionary', max_length=100, null=True, verbose_name='Instagram URL')),
                ('about', wagtail.core.fields.RichTextField(blank=True, help_text='About area/text of the missionary', null=True, verbose_name='About')),
                ('giving_initiative_header', models.CharField(blank=True, help_text='Header for the Giving Initiative section', max_length=100, null=True, verbose_name='Giving Initiative Header')),
                ('giving_initiative_body', models.TextField(blank=True, help_text='Body for the Giving Initiative section', null=True, verbose_name='Giving Initiative Body')),
                ('giving_initiative_goal', models.IntegerField()),
                ('giving_initiative_current_amount', models.IntegerField()),
                ('image', models.ForeignKey(blank=True, help_text='World view image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
