# Generated by Django 2.2.27 on 2022-04-05 16:19

from django.db import migrations, models
import django.db.models.deletion
import home.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('vital_stats_file', models.FileField(blank=True, help_text='PDF file for the vital stats', null=True, upload_to=home.utils.get_upload_path, verbose_name='Vital Stats')),
                ('photos_section', models.ForeignKey(blank=True, help_text='Photos section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photos.PhotoIndexPage', verbose_name='Photos Section')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
