# Generated by Django 2.2.27 on 2022-04-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        ('stories', '0001_initial'),
        ('world_view', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcespage',
            name='stories_section',
            field=models.ForeignKey(blank=True, help_text='Stories section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stories.StoryIndexPage', verbose_name='Stories Section'),
        ),
        migrations.AddField(
            model_name='resourcespage',
            name='videos_section',
            field=models.ForeignKey(blank=True, help_text='Videos section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.VideoIndexPage', verbose_name='Videos Section'),
        ),
        migrations.AddField(
            model_name='resourcespage',
            name='world_view_section',
            field=models.ForeignKey(blank=True, help_text='World view & more section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world_view.WorldViewIndexPage', verbose_name='World View Section'),
        ),
    ]
