# Generated by Django 2.2.28 on 2022-09-21 06:01

from django.db import migrations, models
import django.db.models.deletion
import home.utils
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20220603_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedResourceCenterProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Name of the featured product', max_length=100, verbose_name='Name')),
                ('image', models.ImageField(blank=True, help_text='Image of the featured product', null=True, upload_to=home.utils.get_upload_path, verbose_name='Image')),
                ('image_alt_text', models.CharField(blank=True, help_text='Alt text for the image of the featured resource center product', max_length=100, null=True, verbose_name='Image Alt Text')),
                ('description', models.CharField(blank=True, help_text='Description and price of the featured product', max_length=100, null=True, verbose_name='Price Text')),
                ('footer_text', models.CharField(blank=True, help_text='Footer text of the featured product', max_length=100, null=True, verbose_name='Footer Text')),
                ('url', models.CharField(blank=True, help_text='URL of the store', max_length=150, null=True, verbose_name='URL')),
                ('is_subscription', models.BooleanField(default=False, help_text='Determines whether the product is a subscription-based product or not', verbose_name='Is Subscription')),
                ('subscription_link', models.CharField(blank=True, help_text='Link to the subscription-based product', max_length=150, null=True, verbose_name='Subscription URL')),
                ('page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_resource_products', to='resources.ResourcesPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
