# Generated by Django 2.2.28 on 2022-10-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_featuredresourcecenterproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcespage',
            name='agwm_shop_url',
            field=models.CharField(blank=True, help_text='Set url to AGWM shop', max_length=255, null=True, verbose_name='AGWM Shop URL'),
        ),
    ]
