# Generated by Django 2.2.28 on 2022-11-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resourcespage_agwm_shop_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedResourceCenterProduct',
        ),
    ]
