# Generated by Django 2.2.28 on 2022-12-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20221128_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcespage',
            name='resource_center_sub_title',
            field=models.CharField(blank=True, help_text='Set the text for the Resource Center Sub Title', max_length=255, null=True, verbose_name='Resource Center Sub Title'),
        ),
    ]
