# Generated by Django 2.2.28 on 2022-11-28 05:40

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20220603_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoindexpage',
            name='modal_download_image_button',
            field=models.CharField(blank=True, help_text='Set text for download image button', max_length=100, null=True, verbose_name='Download Image Button Text'),
        ),
        migrations.AddField(
            model_name='photoindexpage',
            name='modal_usage_description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Set text for Usage Description', null=True, verbose_name='Usage Description Text'),
        ),
        migrations.AddField(
            model_name='photoindexpage',
            name='modal_usage_header',
            field=models.CharField(blank=True, help_text='Set text for Usage Rights & Citation Header', max_length=255, null=True, verbose_name='Usage Rights & Citation Header Text'),
        ),
    ]
