# Generated by Django 2.2.28 on 2022-06-23 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header_image_alt_text', models.CharField(blank=True, help_text='Alt text for the header image', max_length=255, null=True, verbose_name='Header Image Alt Text')),
                ('header_title', models.CharField(blank=True, help_text='Title text that will be shown in the header porition of the page', max_length=255, null=True, verbose_name='Header Title')),
                ('header_body', models.TextField(blank=True, help_text='Text that will be shown under the header', null=True, verbose_name='Header Body')),
                ('reaching_background_image_alt_text', models.CharField(blank=True, help_text='Alt text for the reaching background image', max_length=255, null=True, verbose_name='Reaching Background Image Alt Text')),
                ('reaching_title', models.CharField(blank=True, help_text='Title text for the reaching section', max_length=255, null=True, verbose_name='Reaching Title')),
                ('reaching_body', models.TextField(blank=True, help_text='Text that will be shown under the reaching title', null=True, verbose_name='Reaching Body')),
                ('planting_background_image_alt_text', models.CharField(blank=True, help_text='Alt text for the planting background image', max_length=255, null=True, verbose_name='Planting Background Image Alt Text')),
                ('planting_title', models.CharField(blank=True, help_text='Title text for the planting section', max_length=255, null=True, verbose_name='Planting Title')),
                ('planting_body', models.TextField(blank=True, help_text='Text that will be shown under the planting title', null=True, verbose_name='Planting Body')),
                ('training_background_image_alt_text', models.CharField(blank=True, help_text='Alt text for the training background image', max_length=255, null=True, verbose_name='Training Background Image Alt Text')),
                ('training_title', models.CharField(blank=True, help_text='Title text for the Training section', max_length=255, null=True, verbose_name='Training Title')),
                ('training_body', models.TextField(blank=True, help_text='Text that will be shown under the Training title', null=True, verbose_name='Training Body')),
                ('serving_background_image_alt_text', models.CharField(blank=True, help_text='Alt text for the serving background image', max_length=255, null=True, verbose_name='Serving Background Image Alt Text')),
                ('serving_title', models.CharField(blank=True, help_text='Title text for the Serving section', max_length=255, null=True, verbose_name='Serving Title')),
                ('serving_body', models.TextField(blank=True, help_text='Text that will be shown under the Serving title', null=True, verbose_name='Serving Body')),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header Image')),
                ('planting_background_image', models.ForeignKey(blank=True, help_text='Background image of the planting section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Planting Background Image')),
                ('reaching_background_image', models.ForeignKey(blank=True, help_text='Background image of the reaching section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Reaching Background Image')),
                ('serving_background_image', models.ForeignKey(blank=True, help_text='Background image of the serving section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header Image')),
                ('training_background_image', models.ForeignKey(blank=True, help_text='Background Image of the training section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Training Background Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
