# Generated by Django 2.2.28 on 2022-07-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategypage',
            name='serving_background_image',
            field=models.ForeignKey(blank=True, help_text='Background image of the serving section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Serving Background Image'),
        ),
    ]
