# Generated by Django 2.2.28 on 2022-11-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0003_auto_20221128_0829"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategypage",
            name="cta_give_button",
            field=models.CharField(
                blank=True,
                help_text="Text of the Give button in the CTA section",
                max_length=100,
                null=True,
                verbose_name="CTA Give Button Text",
            ),
        ),
        migrations.AddField(
            model_name="strategypage",
            name="cta_go_button",
            field=models.CharField(
                blank=True,
                help_text="Text of the Go button in the CTA section",
                max_length=100,
                null=True,
                verbose_name="CTA Go Button Text",
            ),
        ),
        migrations.AddField(
            model_name="strategypage",
            name="cta_pray_button",
            field=models.CharField(
                blank=True,
                help_text="Text of the Pray button in the CTA section",
                max_length=100,
                null=True,
                verbose_name="CTA Pray Button Text",
            ),
        ),
    ]
