# Generated by Django 2.2.28 on 2022-06-15 02:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header_image_alt_text', models.CharField(blank=True, help_text='Alt text for the header image of the page', max_length=255, null=True, verbose_name='Header Image Alt Text')),
                ('contributions_faq', wagtail.core.fields.RichTextField(blank=True, help_text='Content under the contributions faq section', null=True, verbose_name='contributions_faq')),
                ('online_commitment_forms', wagtail.core.fields.RichTextField(blank=True, help_text='Content under the online commitment forms section', null=True, verbose_name='Other Commitment Forms')),
                ('downloadable_commitment_forms', wagtail.core.fields.RichTextField(blank=True, help_text='Content under the downloadable commitment forms section', null=True, verbose_name='Downloadable Commitment Forms')),
                ('other_online_contributions', wagtail.core.fields.RichTextField(blank=True, help_text='Content under the other online contributions section', null=True, verbose_name='Other Online Contributions')),
                ('automatic_monthly_contributions', wagtail.core.fields.RichTextField(blank=True, help_text='Content under the automatic monthly contributions section', null=True, verbose_name='Automatic Monthly Contributions')),
                ('claiming_world_missions_ministries_credit', wagtail.core.fields.RichTextField(blank=True, help_text='Content under the claiming world missions ministries credit section', null=True, verbose_name='Claiming World Missions Ministries Credit')),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image that is going to be displayed for the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
