# Generated by Django 2.2.28 on 2022-12-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='automatic_monthly_contributions_text',
            field=models.CharField(blank=True, help_text='Automatic monthly contribution text shown in dropdown.', max_length=255, null=True, verbose_name='Automatic Monthly Contribution Text'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='claiming_world_missions_ministries_credit_text',
            field=models.CharField(blank=True, help_text='Claiming world missions ministries credit text shown in dropdown.', max_length=255, null=True, verbose_name='Claiming World Missions Ministries Credit Text'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='contributions_faq_text',
            field=models.CharField(blank=True, help_text='Contribution faq text shown in dropdown.', max_length=255, null=True, verbose_name='Contribution FAQ Text'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='downloadable_commitment_forms_text',
            field=models.CharField(blank=True, help_text='Downloadable commitment forms text shown in dropdown.', max_length=255, null=True, verbose_name='Downloadable Commitment Forms Text'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='online_commitment_forms_text',
            field=models.CharField(blank=True, help_text='Online commitment forms text shown in dropdown.', max_length=255, null=True, verbose_name='Other Commitment Forms Text'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='other_online_contributions_text',
            field=models.CharField(blank=True, help_text='Other online contribution text shown in dropdown.', max_length=255, null=True, verbose_name='Other Online Contribution Text'),
        ),
    ]
