# Generated by Django 2.2.28 on 2022-12-14 04:00

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20221209_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpage',
            name='online_commitment_forms',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Content under the online commitment forms section', null=True, verbose_name='Online Commitment Forms'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='online_commitment_forms_text',
            field=models.CharField(blank=True, help_text='Online commitment forms text shown in dropdown.', max_length=255, null=True, verbose_name='Online Commitment Forms Text'),
        ),
    ]
