# Generated by Django 2.2.28 on 2022-05-23 14:38

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('legacy_giving_header', models.CharField(blank=True, help_text='Title that will be shown in the header portion of the page', max_length=255, null=True, verbose_name='Legacy Giving Header')),
                ('legacy_giving_header_body', models.CharField(blank=True, help_text='Text that will be shown in the body portion in the header of the page', max_length=255, null=True, verbose_name='Header Body')),
                ('header_image_alt_text', models.CharField(blank=True, help_text='Alt text for the header image', max_length=255, null=True, verbose_name='Header Image Alt Text')),
                ('legacy_content_title', models.CharField(blank=True, help_text='Title the will be shown in the content portion of the page', max_length=255, null=True, verbose_name='Legacy Content Title')),
                ('legacy_content_body', wagtail.core.fields.RichTextField(blank=True, help_text='Content of the body that will be shown in the content portion of the page', null=True, verbose_name='Legacy Content Body')),
                ('header_image', models.ForeignKey(blank=True, help_text='Image that will be displayed in the header section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Legacy Page',
                'verbose_name_plural': 'Legay Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
