# Generated by Django 2.2.28 on 2022-12-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacypage',
            name='header_give_now_button_text',
            field=models.CharField(blank=True, help_text='Give now button text in the header.', max_length=255, null=True, verbose_name='Header Give Now Button Text'),
        ),
        migrations.AddField(
            model_name='legacypage',
            name='methods_of_planned_giving_box_1_text',
            field=models.CharField(blank=True, help_text='Text that will be shown in first box of Methods of Planned Giving section.', max_length=255, null=True, verbose_name='Methods of Planned Giving Box 1 Text'),
        ),
        migrations.AddField(
            model_name='legacypage',
            name='methods_of_planned_giving_box_2_text',
            field=models.CharField(blank=True, help_text='Text that will be shown in second box of Methods of Planned Giving section.', max_length=255, null=True, verbose_name='Methods of Planned Giving Box 2 Text'),
        ),
        migrations.AddField(
            model_name='legacypage',
            name='methods_of_planned_giving_box_3_text',
            field=models.CharField(blank=True, help_text='Text that will be shown in third box of Methods of Planned Giving section.', max_length=255, null=True, verbose_name='Methods of Planned Giving Box 3 Text'),
        ),
        migrations.AddField(
            model_name='legacypage',
            name='methods_of_planned_giving_box_4_text',
            field=models.CharField(blank=True, help_text='Text that will be shown in fourth box of Methods of Planned Giving section.', max_length=255, null=True, verbose_name='Methods of Planned Giving Box 4 Text'),
        ),
        migrations.AddField(
            model_name='legacypage',
            name='methods_of_planned_giving_box_5_text',
            field=models.CharField(blank=True, help_text='Text that will be shown in fifth box of Methods of Planned Giving section.', max_length=255, null=True, verbose_name='Methods of Planned Giving Box 5 Text'),
        ),
        migrations.AddField(
            model_name='legacypage',
            name='methods_of_planned_giving_box_6_text',
            field=models.CharField(blank=True, help_text='Text that will be shown in last box of Methods of Planned Giving section.', max_length=255, null=True, verbose_name='Methods of Planned Giving Box 6 Text'),
        ),
        migrations.AddField(
            model_name='legacypage',
            name='methods_of_planned_giving_header_text',
            field=models.CharField(blank=True, help_text='Text that will be shown in the header of methods of plannged giving section.', max_length=255, null=True, verbose_name='Methods of Planned Giving Header Text'),
        ),
        migrations.AddField(
            model_name='legacypage',
            name='start_giving_secetion_button_text',
            field=models.CharField(blank=True, help_text='Text that will be shown in button of Start Giving Section.', max_length=255, null=True, verbose_name='Start Giving Section Button Text'),
        ),
        migrations.AddField(
            model_name='legacypage',
            name='start_giving_secetion_content',
            field=models.TextField(blank=True, help_text='Text that will be shown in content of Start Giving Section.', null=True, verbose_name='Start Giving Section Header Text'),
        ),
        migrations.AddField(
            model_name='legacypage',
            name='start_giving_secetion_header',
            field=models.CharField(blank=True, help_text='Text that will be shown in header of Start Giving Section.', max_length=255, null=True, verbose_name='Start Giving Section Header Text'),
        ),
    ]
