# Generated by Django 2.2.28 on 2022-12-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0002_auto_20221213_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legacypage',
            old_name='start_giving_secetion_button_text',
            new_name='start_giving_section_button_text',
        ),
        migrations.RenameField(
            model_name='legacypage',
            old_name='start_giving_secetion_header',
            new_name='start_giving_section_header',
        ),
        migrations.RemoveField(
            model_name='legacypage',
            name='start_giving_secetion_content',
        ),
        migrations.AddField(
            model_name='legacypage',
            name='start_giving_section_content',
            field=models.TextField(blank=True, help_text='Text that will be shown in content of Start Giving Section.', null=True, verbose_name='Start Giving Section Content'),
        ),
    ]
