# Generated by Django 2.2.28 on 2022-06-10 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('stories', '0004_auto_20220603_0429'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header_image_alt_text', models.CharField(blank=True, help_text='Alt text for the header image', max_length=100, null=True, verbose_name='Header Image Alt Text')),
                ('header_title', models.CharField(blank=True, help_text='Title text that will be shown in the header of the page', max_length=255, null=True, verbose_name='Header Title')),
                ('header_content', models.TextField(blank=True, help_text='Text that will be shown below the header title', null=True, verbose_name='Header Content')),
                ('first_section_title', models.CharField(blank=True, help_text="Title section for the first section of the page. Example 'Explore Ways to Serve'", max_length=255, null=True, verbose_name='First Title')),
                ('first_section_description', models.TextField(blank=True, help_text='Text under the first section title', null=True, verbose_name='First Section Description')),
                ('first_section_short_term_image_alt_text', models.CharField(blank=True, help_text='Alt text for the first section short term image', max_length=100, null=True, verbose_name='First Section Short Term Image Alt Text')),
                ('first_section_one_to_two_year_image_alt_text', models.CharField(blank=True, help_text='Alt text for the first section one to two year image', max_length=100, null=True, verbose_name='First Section One To Two Year Image Alt Text')),
                ('first_section_career_image_alt_text', models.CharField(blank=True, help_text='Alt text for the first section career image', max_length=100, null=True, verbose_name='First Section Career Image Alt Text')),
                ('second_section_title', models.CharField(blank=True, help_text="Title for the second section of the page. Example 'Discover your calling'", max_length=255, null=True, verbose_name='Second Section Title')),
                ('second_section_description', models.TextField(blank=True, help_text='Text under the discover second section title', null=True, verbose_name='Second Section Description')),
                ('second_section_video_url', models.CharField(blank=True, help_text='Video URL for the second section of the page. Make sure that it is the embed URL of the video or else it will not work properly.', max_length=255, null=True, verbose_name='Second Section Video URL')),
                ('second_section_background_image_alt_text', models.CharField(blank=True, help_text='Alt text for the second section background image', max_length=100, null=True, verbose_name='Second Section Background Image Alt Text')),
                ('second_section_video_thumbnail_image_alt_text', models.CharField(blank=True, help_text='Alt text for the thumbnail image that will be shown for the second section video', max_length=255, null=True, verbose_name='Discover Video Thumbnail Image Alt Text')),
                ('short_term_image_alt_text', models.CharField(blank=True, help_text='Alt text for the short term image', max_length=100, null=True, verbose_name='Short Term Image Alt Text')),
                ('one_to_two_year_image_alt_text', models.CharField(blank=True, help_text='Alt text for the one to two year image', max_length=100, null=True, verbose_name='One To Two Year Image Alt Text')),
                ('career_image_alt_text', models.CharField(blank=True, help_text='Alt text for the career image', max_length=100, null=True, verbose_name='Career Image Alt Text')),
                ('start_your_journey_title', models.CharField(blank=True, help_text='Text that will be shown as the title of the Start Your Journey section', max_length=255, null=True, verbose_name='Start Your Journey Title')),
                ('start_your_journey_content', models.CharField(blank=True, help_text='Text that will be shown as the content under the title of the Start Your Journey section', max_length=255, null=True, verbose_name='Start Your Journey Content')),
                ('start_your_journey_background_image_alt_text', models.CharField(blank=True, help_text='Alt text for the start your journey background image', max_length=100, null=True, verbose_name='Start Your Journey Background Image Alt Text')),
                ('career_image', models.ForeignKey(blank=True, help_text='Image that will be shown for the career', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Career Image')),
                ('first_section_career_image', models.ForeignKey(blank=True, help_text='Image that will be shown for the first section career', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='First Section Career Image')),
                ('first_section_one_to_two_year_image', models.ForeignKey(blank=True, help_text='Image that will be shown for the first section One to Two year', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='First Section One To Two Year Image')),
                ('first_section_short_term_image', models.ForeignKey(blank=True, help_text='Image that will be shown for the first section short term', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='First Section Short Term Image')),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Header Image')),
                ('one_to_two_year_image', models.ForeignKey(blank=True, help_text='Image that will be shown for the one to two year', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='One to Two Year Image')),
                ('second_section_background_image', models.ForeignKey(blank=True, help_text='Background image that will be shown for the second section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Second Section Background Image')),
                ('second_section_video_thumbnail_image', models.ForeignKey(blank=True, help_text='The thumbnail image that will be shown for the second section video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Discover Video Thumbnail Image')),
                ('short_term_image', models.ForeignKey(blank=True, help_text='Image that will be shown for the first section short term', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Short Term Image')),
                ('start_your_journey_background_image', models.ForeignKey(blank=True, help_text='Image that will be shown start your journey background', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Start Your Journey Background Image')),
                ('stories_section', models.ForeignKey(blank=True, help_text='Stories section of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stories.StoryIndexPage', verbose_name='Stories Section')),
            ],
            options={
                'verbose_name': 'Go Page',
                'verbose_name_plural': 'Go Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
