# Generated by Django 2.2.28 on 2022-06-27 13:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('go', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gopage',
            name='first_section_career_image',
        ),
        migrations.RemoveField(
            model_name='gopage',
            name='first_section_career_image_alt_text',
        ),
        migrations.RemoveField(
            model_name='gopage',
            name='first_section_description',
        ),
        migrations.RemoveField(
            model_name='gopage',
            name='first_section_one_to_two_year_image',
        ),
        migrations.RemoveField(
            model_name='gopage',
            name='first_section_one_to_two_year_image_alt_text',
        ),
        migrations.RemoveField(
            model_name='gopage',
            name='first_section_short_term_image',
        ),
        migrations.RemoveField(
            model_name='gopage',
            name='first_section_short_term_image_alt_text',
        ),
        migrations.RemoveField(
            model_name='gopage',
            name='first_section_title',
        ),
        migrations.RemoveField(
            model_name='gopage',
            name='second_section_background_image',
        ),
        migrations.RemoveField(
            model_name='gopage',
            name='second_section_background_image_alt_text',
        ),
        migrations.RemoveField(
            model_name='gopage',
            name='second_section_description',
        ),
        migrations.RemoveField(
            model_name='gopage',
            name='second_section_title',
        ),
        migrations.RemoveField(
            model_name='gopage',
            name='second_section_video_thumbnail_image',
        ),
        migrations.RemoveField(
            model_name='gopage',
            name='second_section_video_thumbnail_image_alt_text',
        ),
        migrations.RemoveField(
            model_name='gopage',
            name='second_section_video_url',
        ),
        migrations.AddField(
            model_name='gopage',
            name='ways_to_serve_bottom_text',
            field=models.TextField(blank=True, help_text='Text that will be shown at the bottom part of the title in the Ways To Serve section', null=True, verbose_name='Ways To Serve Bottom Text'),
        ),
        migrations.AddField(
            model_name='gopage',
            name='ways_to_serve_title',
            field=models.CharField(blank=True, help_text='Title text that will be shown in the Ways to Serve section', max_length=255, null=True, verbose_name='Ways To Serve Title'),
        ),
        migrations.CreateModel(
            name='SpecialGivingPageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_video', models.BooleanField(default=False, help_text='Set this as true if the item in the gallery is a Video', verbose_name='Is Video')),
                ('video_url', models.TextField(blank=True, help_text='URL of the video to be shown. This needs to be the EMBED url of the video or else it will not work properly', null=True, verbose_name='Video URL')),
                ('image_alt_text', models.CharField(blank=True, help_text='Alt text for the image', max_length=255, null=True, verbose_name='Image Alt Text')),
                ('image', models.ForeignKey(blank=True, help_text='Image for the go page gallery. This also serves as the thumbnail if the item of the gallery is a video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='go_gallery', to='go.GoPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
