# Generated by Django 2.2.28 on 2022-11-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0003_auto_20221107_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='gopage',
            name='start_your_journey_first_button_name',
            field=models.CharField(blank=True, help_text='Set the name of the first button', max_length=50, null=True, verbose_name='Start Your Journey First Button Name'),
        ),
        migrations.AddField(
            model_name='gopage',
            name='start_your_journey_second_button_name',
            field=models.CharField(blank=True, help_text='Set the name of the second button', max_length=50, null=True, verbose_name='Start Your Journey Second Button Name'),
        ),
        migrations.AddField(
            model_name='gopage',
            name='start_your_journey_third_button_name',
            field=models.CharField(blank=True, help_text='Set the name of the third button', max_length=50, null=True, verbose_name='Start Your Journey Third Button Name'),
        ),
    ]
