# Generated by Django 2.2.28 on 2022-11-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0004_auto_20221107_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='gopage',
            name='are_you_called_button',
            field=models.CharField(blank=True, help_text='Are you called button text that will be shown in the take the quiz section', max_length=100, null=True, verbose_name='Are you Called Button Text'),
        ),
        migrations.AddField(
            model_name='gopage',
            name='career_text',
            field=models.CharField(blank=True, help_text='Set text for Career', max_length=100, null=True, verbose_name='Career Text'),
        ),
        migrations.AddField(
            model_name='gopage',
            name='has_quiz',
            field=models.BooleanField(default=False, help_text='Set this as true to display the Take the Quiz section in Go Page', null=True, verbose_name='Has Quiz'),
        ),
        migrations.AddField(
            model_name='gopage',
            name='one_to_two_year_text',
            field=models.CharField(blank=True, help_text='Set text for One to Two Year', max_length=100, null=True, verbose_name='One to Two Year Text'),
        ),
        migrations.AddField(
            model_name='gopage',
            name='short_term_text',
            field=models.CharField(blank=True, help_text='Set text for Short Term', max_length=100, null=True, verbose_name='Short Term Text'),
        ),
        migrations.AddField(
            model_name='gopage',
            name='stories_header_sub_title',
            field=models.CharField(blank=True, help_text='Set text for Stories Header Sub Title', max_length=255, null=True, verbose_name='Stories Header Sub Title'),
        ),
        migrations.AddField(
            model_name='gopage',
            name='stories_header_title',
            field=models.CharField(blank=True, help_text='Set text for Stories Header', max_length=255, null=True, verbose_name='Stories Header Title'),
        ),
        migrations.AddField(
            model_name='gopage',
            name='stories_read_all_button_text',
            field=models.CharField(blank=True, help_text='Set text for Stories Read All Button', max_length=255, null=True, verbose_name='Stories Read All Button Text'),
        ),
        migrations.AddField(
            model_name='gopage',
            name='take_the_quiz_button',
            field=models.CharField(blank=True, help_text='Take the quiz button text that will be shown', max_length=100, null=True, verbose_name='Take The Quiz Button Text'),
        ),
    ]
