# Generated by Django 2.2.28 on 2022-08-30 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    def add_notification_to_existing_users(apps, schema_editor):
        UserNotification = apps.get_model("users", "UserNotification")
        User = apps.get_model("users", "User")

        for user in User.objects.all():
            UserNotification.objects.create(user=user)

    operations = [
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prayer_push_notification",
                    models.BooleanField(
                        default=False, verbose_name="Prayer Push Notification"
                    ),
                ),
                (
                    "prayer_email_notification",
                    models.BooleanField(
                        default=False, verbose_name="Prayer Email Notification"
                    ),
                ),
                (
                    "email_push_notification",
                    models.BooleanField(
                        default=False, verbose_name="Email Push Notification"
                    ),
                ),
                (
                    "email_email_notification",
                    models.BooleanField(
                        default=False, verbose_name="Email Email Notification"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notification",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Notification",
                "verbose_name_plural": "User Notifications",
            },
        ),
        migrations.RunPython(
            add_notification_to_existing_users, migrations.RunPython.noop
        ),
    ]
