# Generated by Django 2.2.28 on 2022-08-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='email_push_notification',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='prayer_push_notification',
        ),
    ]
