# Generated by Django 2.2.28 on 2022-09-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220830_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='giving_initiatives_email_notification',
            field=models.BooleanField(default=False, verbose_name='Giving Initiatives Email Notification'),
        ),
        migrations.AddField(
            model_name='user',
            name='prayer_email_notification',
            field=models.BooleanField(default=False, verbose_name='Prayer Email Notification'),
        ),
        migrations.AddField(
            model_name='user',
            name='stories_email_notification',
            field=models.BooleanField(default=False, verbose_name='Stories Email Notification'),
        ),
        migrations.AddField(
            model_name='user',
            name='timely_update_and_news_notification',
            field=models.BooleanField(default=False, verbose_name='Timely Update and News Notification'),
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
