# Generated by Django 2.2.28 on 2022-10-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220929_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='timely_update_and_news_notification',
        ),
    ]
